// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`Deposit`](crate::operation::deposit::builders::DepositFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::deposit::builders::DepositFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::deposit::builders::DepositFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`source_ifsc(impl Into<String>)`](crate::operation::deposit::builders::DepositFluentBuilder::source_ifsc) / [`set_source_ifsc(Option<String>)`](crate::operation::deposit::builders::DepositFluentBuilder::set_source_ifsc):<br>required: **true**<br>(undocumented)<br>
    ///   - [`source_account_number(impl Into<String>)`](crate::operation::deposit::builders::DepositFluentBuilder::source_account_number) / [`set_source_account_number(Option<String>)`](crate::operation::deposit::builders::DepositFluentBuilder::set_source_account_number):<br>required: **true**<br>(undocumented)<br>
    ///   - [`amount(i64)`](crate::operation::deposit::builders::DepositFluentBuilder::amount) / [`set_amount(Option<i64>)`](crate::operation::deposit::builders::DepositFluentBuilder::set_amount):<br>required: **true**<br>Monetary amount in the smallest currency unit (e.g., paise for INR).<br>
    ///   - [`pending(bool)`](crate::operation::deposit::builders::DepositFluentBuilder::pending) / [`set_pending(Option<bool>)`](crate::operation::deposit::builders::DepositFluentBuilder::set_pending):<br>required: **false**<br>(undocumented)<br>
    ///   - [`gateway_ref(impl Into<String>)`](crate::operation::deposit::builders::DepositFluentBuilder::gateway_ref) / [`set_gateway_ref(Option<String>)`](crate::operation::deposit::builders::DepositFluentBuilder::set_gateway_ref):<br>required: **false**<br>(undocumented)<br>
    ///   - [`timeout_seconds(i32)`](crate::operation::deposit::builders::DepositFluentBuilder::timeout_seconds) / [`set_timeout_seconds(Option<i32>)`](crate::operation::deposit::builders::DepositFluentBuilder::set_timeout_seconds):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`DepositOutput`](crate::operation::deposit::DepositOutput) with field(s):
    ///   - [`deposit_id(String)`](crate::operation::deposit::DepositOutput::deposit_id): (undocumented)
    ///   - [`account_id(String)`](crate::operation::deposit::DepositOutput::account_id): (undocumented)
    ///   - [`amount(i64)`](crate::operation::deposit::DepositOutput::amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`pool(String)`](crate::operation::deposit::DepositOutput::pool): (undocumented)
    ///   - [`status(String)`](crate::operation::deposit::DepositOutput::status): (undocumented)
    ///   - [`gateway_ref(Option<String>)`](crate::operation::deposit::DepositOutput::gateway_ref): (undocumented)
    ///   - [`timeout_seconds(Option<i32>)`](crate::operation::deposit::DepositOutput::timeout_seconds): (undocumented)
                            /// - On failure, responds with [`SdkError<DepositError>`](crate::operation::deposit::DepositError)
    pub fn deposit(&self) -> crate::operation::deposit::builders::DepositFluentBuilder {
                                crate::operation::deposit::builders::DepositFluentBuilder::new(self.handle.clone())
                            }
}

