// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetNormalAccount`](crate::operation::get_normal_account::builders::GetNormalAccountFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::get_normal_account::builders::GetNormalAccountFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::get_normal_account::builders::GetNormalAccountFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetNormalAccountOutput`](crate::operation::get_normal_account::GetNormalAccountOutput) with field(s):
    ///   - [`id(String)`](crate::operation::get_normal_account::GetNormalAccountOutput::id): (undocumented)
    ///   - [`holder_id(String)`](crate::operation::get_normal_account::GetNormalAccountOutput::holder_id): (undocumented)
    ///   - [`origin_ifsc(Option<String>)`](crate::operation::get_normal_account::GetNormalAccountOutput::origin_ifsc): (undocumented)
    ///   - [`origin_account_number(Option<String>)`](crate::operation::get_normal_account::GetNormalAccountOutput::origin_account_number): (undocumented)
    ///   - [`vpa(Option<String>)`](crate::operation::get_normal_account::GetNormalAccountOutput::vpa): (undocumented)
    ///   - [`virtual_ifsc(Option<String>)`](crate::operation::get_normal_account::GetNormalAccountOutput::virtual_ifsc): (undocumented)
    ///   - [`virtual_account_number(Option<String>)`](crate::operation::get_normal_account::GetNormalAccountOutput::virtual_account_number): (undocumented)
    ///   - [`kyc_tier(String)`](crate::operation::get_normal_account::GetNormalAccountOutput::kyc_tier): (undocumented)
    ///   - [`status(String)`](crate::operation::get_normal_account::GetNormalAccountOutput::status): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::get_normal_account::GetNormalAccountOutput::created_at): ISO 8601 date-time.
    ///   - [`updated_at(DateTime)`](crate::operation::get_normal_account::GetNormalAccountOutput::updated_at): ISO 8601 date-time.
                            /// - On failure, responds with [`SdkError<GetNormalAccountError>`](crate::operation::get_normal_account::GetNormalAccountError)
    pub fn get_normal_account(&self) -> crate::operation::get_normal_account::builders::GetNormalAccountFluentBuilder {
                                crate::operation::get_normal_account::builders::GetNormalAccountFluentBuilder::new(self.handle.clone())
                            }
}

