// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetNormalAccountBalance`](crate::operation::get_normal_account_balance::builders::GetNormalAccountBalanceFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::get_normal_account_balance::builders::GetNormalAccountBalanceFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::get_normal_account_balance::builders::GetNormalAccountBalanceFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetNormalAccountBalanceOutput`](crate::operation::get_normal_account_balance::GetNormalAccountBalanceOutput) with field(s):
    ///   - [`account_id(String)`](crate::operation::get_normal_account_balance::GetNormalAccountBalanceOutput::account_id): (undocumented)
    ///   - [`balance(i64)`](crate::operation::get_normal_account_balance::GetNormalAccountBalanceOutput::balance): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`pending(i64)`](crate::operation::get_normal_account_balance::GetNormalAccountBalanceOutput::pending): Monetary amount in the smallest currency unit (e.g., paise for INR).
                            /// - On failure, responds with [`SdkError<GetNormalAccountBalanceError>`](crate::operation::get_normal_account_balance::GetNormalAccountBalanceError)
    pub fn get_normal_account_balance(&self) -> crate::operation::get_normal_account_balance::builders::GetNormalAccountBalanceFluentBuilder {
                                crate::operation::get_normal_account_balance::builders::GetNormalAccountBalanceFluentBuilder::new(self.handle.clone())
                            }
}

