// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetAccount`](crate::operation::get_account::builders::GetAccountFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::get_account::builders::GetAccountFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::get_account::builders::GetAccountFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetAccountOutput`](crate::operation::get_account::GetAccountOutput) with field(s):
    ///   - [`id(String)`](crate::operation::get_account::GetAccountOutput::id): (undocumented)
    ///   - [`holder_id(String)`](crate::operation::get_account::GetAccountOutput::holder_id): (undocumented)
    ///   - [`purpose_code(String)`](crate::operation::get_account::GetAccountOutput::purpose_code): (undocumented)
    ///   - [`origin_ifsc(String)`](crate::operation::get_account::GetAccountOutput::origin_ifsc): (undocumented)
    ///   - [`origin_account_number(String)`](crate::operation::get_account::GetAccountOutput::origin_account_number): (undocumented)
    ///   - [`vpa(Option<String>)`](crate::operation::get_account::GetAccountOutput::vpa): (undocumented)
    ///   - [`virtual_ifsc(Option<String>)`](crate::operation::get_account::GetAccountOutput::virtual_ifsc): (undocumented)
    ///   - [`virtual_account_number(Option<String>)`](crate::operation::get_account::GetAccountOutput::virtual_account_number): (undocumented)
    ///   - [`kyc_tier(String)`](crate::operation::get_account::GetAccountOutput::kyc_tier): (undocumented)
    ///   - [`status(String)`](crate::operation::get_account::GetAccountOutput::status): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::get_account::GetAccountOutput::created_at): ISO 8601 date-time.
    ///   - [`updated_at(DateTime)`](crate::operation::get_account::GetAccountOutput::updated_at): ISO 8601 date-time.
                            /// - On failure, responds with [`SdkError<GetAccountError>`](crate::operation::get_account::GetAccountError)
    pub fn get_account(&self) -> crate::operation::get_account::builders::GetAccountFluentBuilder {
                                crate::operation::get_account::builders::GetAccountFluentBuilder::new(self.handle.clone())
                            }
}

