// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetPurposeType`](crate::operation::get_purpose_type::builders::GetPurposeTypeFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`purpose_code(impl Into<String>)`](crate::operation::get_purpose_type::builders::GetPurposeTypeFluentBuilder::purpose_code) / [`set_purpose_code(Option<String>)`](crate::operation::get_purpose_type::builders::GetPurposeTypeFluentBuilder::set_purpose_code):<br>required: **true**<br>(undocumented)<br>
    /// - On success, responds with [`GetPurposeTypeOutput`](crate::operation::get_purpose_type::GetPurposeTypeOutput) with field(s):
    ///   - [`purpose_code(String)`](crate::operation::get_purpose_type::GetPurposeTypeOutput::purpose_code): (undocumented)
    ///   - [`allowed_mccs(Vec::<MccEntry>)`](crate::operation::get_purpose_type::GetPurposeTypeOutput::allowed_mccs): (undocumented)
    /// - On failure, responds with [`SdkError<GetPurposeTypeError>`](crate::operation::get_purpose_type::GetPurposeTypeError)
    pub fn get_purpose_type(&self) -> crate::operation::get_purpose_type::builders::GetPurposeTypeFluentBuilder {
        crate::operation::get_purpose_type::builders::GetPurposeTypeFluentBuilder::new(self.handle.clone())
    }
}
