// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetPBAccountContributionSummary`](crate::operation::get_pb_account_contribution_summary::builders::GetPBAccountContributionSummaryFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::get_pb_account_contribution_summary::builders::GetPBAccountContributionSummaryFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::get_pb_account_contribution_summary::builders::GetPBAccountContributionSummaryFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetPbAccountContributionSummaryOutput`](crate::operation::get_pb_account_contribution_summary::GetPbAccountContributionSummaryOutput) with field(s):
    ///   - [`trust(FundingTypeSummary)`](crate::operation::get_pb_account_contribution_summary::GetPbAccountContributionSummaryOutput::trust): Per-funding-type contribution summary.
    ///   - [`third_party(FundingTypeSummary)`](crate::operation::get_pb_account_contribution_summary::GetPbAccountContributionSummaryOutput::third_party): Per-funding-type contribution summary.
                            /// - On failure, responds with [`SdkError<GetPBAccountContributionSummaryError>`](crate::operation::get_pb_account_contribution_summary::GetPBAccountContributionSummaryError)
    pub fn get_pb_account_contribution_summary(&self) -> crate::operation::get_pb_account_contribution_summary::builders::GetPBAccountContributionSummaryFluentBuilder {
                                crate::operation::get_pb_account_contribution_summary::builders::GetPBAccountContributionSummaryFluentBuilder::new(self.handle.clone())
                            }
}

