// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListNormalAccountTransactions`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`offset(i64)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::offset) / [`set_offset(Option<i64>)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::set_offset):<br>required: **false**<br>(undocumented)<br>
    ///   - [`limit(i64)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::limit) / [`set_limit(Option<i64>)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::set_limit):<br>required: **false**<br>(undocumented)<br>
    ///   - [`from_date(DateTime)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::from_date) / [`set_from_date(Option<DateTime>)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::set_from_date):<br>required: **false**<br>ISO 8601 date-time.<br>
    ///   - [`to_date(DateTime)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::to_date) / [`set_to_date(Option<DateTime>)`](crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::set_to_date):<br>required: **false**<br>ISO 8601 date-time.<br>
                            /// - On success, responds with [`ListNormalAccountTransactionsOutput`](crate::operation::list_normal_account_transactions::ListNormalAccountTransactionsOutput) with field(s):
    ///   - [`transactions(Vec::<TransactionSummary>)`](crate::operation::list_normal_account_transactions::ListNormalAccountTransactionsOutput::transactions): (undocumented)
    ///   - [`total(i64)`](crate::operation::list_normal_account_transactions::ListNormalAccountTransactionsOutput::total): (undocumented)
    ///   - [`offset(i64)`](crate::operation::list_normal_account_transactions::ListNormalAccountTransactionsOutput::offset): (undocumented)
    ///   - [`limit(i64)`](crate::operation::list_normal_account_transactions::ListNormalAccountTransactionsOutput::limit): (undocumented)
                            /// - On failure, responds with [`SdkError<ListNormalAccountTransactionsError>`](crate::operation::list_normal_account_transactions::ListNormalAccountTransactionsError)
    pub fn list_normal_account_transactions(&self) -> crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder {
                                crate::operation::list_normal_account_transactions::builders::ListNormalAccountTransactionsFluentBuilder::new(self.handle.clone())
                            }
}

