// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListNormalAccounts`](crate::operation::list_normal_accounts::builders::ListNormalAccountsFluentBuilder) operation.
                            ///
                            /// - The fluent builder takes no input, just [`send`](crate::operation::list_normal_accounts::builders::ListNormalAccountsFluentBuilder::send) it.
                            /// - On success, responds with [`ListNormalAccountsOutput`](crate::operation::list_normal_accounts::ListNormalAccountsOutput) with field(s):
    ///   - [`accounts(Vec::<NormalAccountSummary>)`](crate::operation::list_normal_accounts::ListNormalAccountsOutput::accounts): (undocumented)
    ///   - [`total(i64)`](crate::operation::list_normal_accounts::ListNormalAccountsOutput::total): (undocumented)
    ///   - [`offset(i64)`](crate::operation::list_normal_accounts::ListNormalAccountsOutput::offset): (undocumented)
    ///   - [`limit(i64)`](crate::operation::list_normal_accounts::ListNormalAccountsOutput::limit): (undocumented)
                            /// - On failure, responds with [`SdkError<ListNormalAccountsError>`](crate::operation::list_normal_accounts::ListNormalAccountsError)
    pub fn list_normal_accounts(&self) -> crate::operation::list_normal_accounts::builders::ListNormalAccountsFluentBuilder {
                                crate::operation::list_normal_accounts::builders::ListNormalAccountsFluentBuilder::new(self.handle.clone())
                            }
}

