// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListTransactions`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`offset(i64)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::offset) / [`set_offset(Option<i64>)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::set_offset):<br>required: **false**<br>(undocumented)<br>
    ///   - [`limit(i64)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::limit) / [`set_limit(Option<i64>)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::set_limit):<br>required: **false**<br>(undocumented)<br>
    ///   - [`from_date(DateTime)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::from_date) / [`set_from_date(Option<DateTime>)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::set_from_date):<br>required: **false**<br>ISO 8601 date-time.<br>
    ///   - [`to_date(DateTime)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::to_date) / [`set_to_date(Option<DateTime>)`](crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::set_to_date):<br>required: **false**<br>ISO 8601 date-time.<br>
                            /// - On success, responds with [`ListTransactionsOutput`](crate::operation::list_transactions::ListTransactionsOutput) with field(s):
    ///   - [`transactions(Vec::<TransactionSummary>)`](crate::operation::list_transactions::ListTransactionsOutput::transactions): (undocumented)
    ///   - [`total(i64)`](crate::operation::list_transactions::ListTransactionsOutput::total): (undocumented)
    ///   - [`offset(i64)`](crate::operation::list_transactions::ListTransactionsOutput::offset): (undocumented)
    ///   - [`limit(i64)`](crate::operation::list_transactions::ListTransactionsOutput::limit): (undocumented)
                            /// - On failure, responds with [`SdkError<ListTransactionsError>`](crate::operation::list_transactions::ListTransactionsError)
    #[deprecated(note = "Use ListPBAccountTransactions.", since = "2026-05-08")]
    pub fn list_transactions(&self) -> crate::operation::list_transactions::builders::ListTransactionsFluentBuilder {
                                crate::operation::list_transactions::builders::ListTransactionsFluentBuilder::new(self.handle.clone())
                            }
}

