// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`PostDeposit`](crate::operation::post_deposit::builders::PostDepositFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::post_deposit::builders::PostDepositFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::post_deposit::builders::PostDepositFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`deposit_id(impl Into<String>)`](crate::operation::post_deposit::builders::PostDepositFluentBuilder::deposit_id) / [`set_deposit_id(Option<String>)`](crate::operation::post_deposit::builders::PostDepositFluentBuilder::set_deposit_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`PostDepositOutput`](crate::operation::post_deposit::PostDepositOutput) with field(s):
    ///   - [`deposit_id(String)`](crate::operation::post_deposit::PostDepositOutput::deposit_id): (undocumented)
    ///   - [`account_id(String)`](crate::operation::post_deposit::PostDepositOutput::account_id): (undocumented)
    ///   - [`amount(i64)`](crate::operation::post_deposit::PostDepositOutput::amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`pool(String)`](crate::operation::post_deposit::PostDepositOutput::pool): (undocumented)
    ///   - [`funding_type(Option<String>)`](crate::operation::post_deposit::PostDepositOutput::funding_type): (undocumented)
    ///   - [`status(String)`](crate::operation::post_deposit::PostDepositOutput::status): (undocumented)
    ///   - [`gateway_ref(Option<String>)`](crate::operation::post_deposit::PostDepositOutput::gateway_ref): (undocumented)
    ///   - [`timeout_seconds(Option<i32>)`](crate::operation::post_deposit::PostDepositOutput::timeout_seconds): (undocumented)
                            /// - On failure, responds with [`SdkError<PostDepositError>`](crate::operation::post_deposit::PostDepositError)
    pub fn post_deposit(&self) -> crate::operation::post_deposit::builders::PostDepositFluentBuilder {
                                crate::operation::post_deposit::builders::PostDepositFluentBuilder::new(self.handle.clone())
                            }
}

