// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`PostNormalAccountTransfer`](crate::operation::post_normal_account_transfer::builders::PostNormalAccountTransferFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::post_normal_account_transfer::builders::PostNormalAccountTransferFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::post_normal_account_transfer::builders::PostNormalAccountTransferFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`transfer_id(impl Into<String>)`](crate::operation::post_normal_account_transfer::builders::PostNormalAccountTransferFluentBuilder::transfer_id) / [`set_transfer_id(Option<String>)`](crate::operation::post_normal_account_transfer::builders::PostNormalAccountTransferFluentBuilder::set_transfer_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`PostNormalAccountTransferOutput`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferOutput) with field(s):
    ///   - [`transfer_id(String)`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferOutput::transfer_id): (undocumented)
    ///   - [`source_account_id(String)`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferOutput::source_account_id): (undocumented)
    ///   - [`destination_account_id(String)`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferOutput::destination_account_id): (undocumented)
    ///   - [`amount(i64)`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferOutput::amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`status(String)`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferOutput::status): (undocumented)
    ///   - [`correlation_id(String)`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferOutput::correlation_id): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferOutput::created_at): ISO 8601 date-time.
                            /// - On failure, responds with [`SdkError<PostNormalAccountTransferError>`](crate::operation::post_normal_account_transfer::PostNormalAccountTransferError)
    pub fn post_normal_account_transfer(&self) -> crate::operation::post_normal_account_transfer::builders::PostNormalAccountTransferFluentBuilder {
                                crate::operation::post_normal_account_transfer::builders::PostNormalAccountTransferFluentBuilder::new(self.handle.clone())
                            }
}

