// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`PostNormalAccountDeposit`](crate::operation::post_normal_account_deposit::builders::PostNormalAccountDepositFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::post_normal_account_deposit::builders::PostNormalAccountDepositFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::post_normal_account_deposit::builders::PostNormalAccountDepositFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`deposit_id(impl Into<String>)`](crate::operation::post_normal_account_deposit::builders::PostNormalAccountDepositFluentBuilder::deposit_id) / [`set_deposit_id(Option<String>)`](crate::operation::post_normal_account_deposit::builders::PostNormalAccountDepositFluentBuilder::set_deposit_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`PostNormalAccountDepositOutput`](crate::operation::post_normal_account_deposit::PostNormalAccountDepositOutput) with field(s):
    ///   - [`deposit_id(String)`](crate::operation::post_normal_account_deposit::PostNormalAccountDepositOutput::deposit_id): (undocumented)
    ///   - [`account_id(String)`](crate::operation::post_normal_account_deposit::PostNormalAccountDepositOutput::account_id): (undocumented)
    ///   - [`amount(i64)`](crate::operation::post_normal_account_deposit::PostNormalAccountDepositOutput::amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`status(String)`](crate::operation::post_normal_account_deposit::PostNormalAccountDepositOutput::status): (undocumented)
    ///   - [`gateway_ref(Option<String>)`](crate::operation::post_normal_account_deposit::PostNormalAccountDepositOutput::gateway_ref): (undocumented)
    ///   - [`timeout_seconds(Option<i32>)`](crate::operation::post_normal_account_deposit::PostNormalAccountDepositOutput::timeout_seconds): (undocumented)
                            /// - On failure, responds with [`SdkError<PostNormalAccountDepositError>`](crate::operation::post_normal_account_deposit::PostNormalAccountDepositError)
    pub fn post_normal_account_deposit(&self) -> crate::operation::post_normal_account_deposit::builders::PostNormalAccountDepositFluentBuilder {
                                crate::operation::post_normal_account_deposit::builders::PostNormalAccountDepositFluentBuilder::new(self.handle.clone())
                            }
}

