// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ReverseNormalAccountTransfer`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`transfer_id(impl Into<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::transfer_id) / [`set_transfer_id(Option<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::set_transfer_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`amount(i64)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::amount) / [`set_amount(Option<i64>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::set_amount):<br>required: **true**<br>Monetary amount in the smallest currency unit (e.g., paise for INR).<br>
    ///   - [`pending(bool)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::pending) / [`set_pending(Option<bool>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::set_pending):<br>required: **false**<br>(undocumented)<br>
    ///   - [`gateway_ref(impl Into<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::gateway_ref) / [`set_gateway_ref(Option<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::set_gateway_ref):<br>required: **false**<br>(undocumented)<br>
    ///   - [`timeout_seconds(i32)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::timeout_seconds) / [`set_timeout_seconds(Option<i32>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::set_timeout_seconds):<br>required: **false**<br>(undocumented)<br>
    ///   - [`description(impl Into<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::description) / [`set_description(Option<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::set_description):<br>required: **false**<br>(undocumented)<br>
    ///   - [`idempotency_key(impl Into<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::idempotency_key) / [`set_idempotency_key(Option<String>)`](crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::set_idempotency_key):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`ReverseNormalAccountTransferOutput`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput) with field(s):
    ///   - [`reversal_id(String)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::reversal_id): (undocumented)
    ///   - [`original_transfer_id(String)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::original_transfer_id): (undocumented)
    ///   - [`source_account_id(String)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::source_account_id): (undocumented)
    ///   - [`destination_account_id(String)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::destination_account_id): (undocumented)
    ///   - [`amount(i64)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`original_amount(i64)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::original_amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`status(String)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::status): (undocumented)
    ///   - [`correlation_id(String)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::correlation_id): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferOutput::created_at): ISO 8601 date-time.
                            /// - On failure, responds with [`SdkError<ReverseNormalAccountTransferError>`](crate::operation::reverse_normal_account_transfer::ReverseNormalAccountTransferError)
    pub fn reverse_normal_account_transfer(&self) -> crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder {
                                crate::operation::reverse_normal_account_transfer::builders::ReverseNormalAccountTransferFluentBuilder::new(self.handle.clone())
                            }
}

