// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`TransferToPBAccount`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`destination_pb_account_id(impl Into<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::destination_pb_account_id) / [`set_destination_pb_account_id(Option<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::set_destination_pb_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`amount(i64)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::amount) / [`set_amount(Option<i64>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::set_amount):<br>required: **true**<br>Monetary amount in the smallest currency unit (e.g., paise for INR).<br>
    ///   - [`pending(bool)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::pending) / [`set_pending(Option<bool>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::set_pending):<br>required: **false**<br>(undocumented)<br>
    ///   - [`gateway_ref(impl Into<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::gateway_ref) / [`set_gateway_ref(Option<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::set_gateway_ref):<br>required: **false**<br>(undocumented)<br>
    ///   - [`timeout_seconds(i32)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::timeout_seconds) / [`set_timeout_seconds(Option<i32>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::set_timeout_seconds):<br>required: **false**<br>(undocumented)<br>
    ///   - [`description(impl Into<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::description) / [`set_description(Option<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::set_description):<br>required: **false**<br>(undocumented)<br>
    ///   - [`idempotency_key(impl Into<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::idempotency_key) / [`set_idempotency_key(Option<String>)`](crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::set_idempotency_key):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`TransferToPbAccountOutput`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput) with field(s):
    ///   - [`transfer_id(String)`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput::transfer_id): (undocumented)
    ///   - [`source_account_id(String)`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput::source_account_id): (undocumented)
    ///   - [`destination_account_id(String)`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput::destination_account_id): (undocumented)
    ///   - [`amount(i64)`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput::amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`status(String)`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput::status): (undocumented)
    ///   - [`correlation_id(String)`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput::correlation_id): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput::created_at): ISO 8601 date-time.
                            /// - On failure, responds with [`SdkError<TransferToPBAccountError>`](crate::operation::transfer_to_pb_account::TransferToPBAccountError)
    pub fn transfer_to_pb_account(&self) -> crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder {
                                crate::operation::transfer_to_pb_account::builders::TransferToPBAccountFluentBuilder::new(self.handle.clone())
                            }
}

