// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`UpdateNormalAccountStatus`](crate::operation::update_normal_account_status::builders::UpdateNormalAccountStatusFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::update_normal_account_status::builders::UpdateNormalAccountStatusFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::update_normal_account_status::builders::UpdateNormalAccountStatusFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`status(impl Into<String>)`](crate::operation::update_normal_account_status::builders::UpdateNormalAccountStatusFluentBuilder::status) / [`set_status(Option<String>)`](crate::operation::update_normal_account_status::builders::UpdateNormalAccountStatusFluentBuilder::set_status):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`UpdateNormalAccountStatusOutput`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput) with field(s):
    ///   - [`id(String)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::id): (undocumented)
    ///   - [`holder_id(String)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::holder_id): (undocumented)
    ///   - [`origin_ifsc(Option<String>)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::origin_ifsc): (undocumented)
    ///   - [`origin_account_number(Option<String>)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::origin_account_number): (undocumented)
    ///   - [`vpa(Option<String>)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::vpa): (undocumented)
    ///   - [`virtual_ifsc(Option<String>)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::virtual_ifsc): (undocumented)
    ///   - [`virtual_account_number(Option<String>)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::virtual_account_number): (undocumented)
    ///   - [`kyc_tier(String)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::kyc_tier): (undocumented)
    ///   - [`status(String)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::status): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::created_at): ISO 8601 date-time.
    ///   - [`updated_at(DateTime)`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusOutput::updated_at): ISO 8601 date-time.
                            /// - On failure, responds with [`SdkError<UpdateNormalAccountStatusError>`](crate::operation::update_normal_account_status::UpdateNormalAccountStatusError)
    pub fn update_normal_account_status(&self) -> crate::operation::update_normal_account_status::builders::UpdateNormalAccountStatusFluentBuilder {
                                crate::operation::update_normal_account_status::builders::UpdateNormalAccountStatusFluentBuilder::new(self.handle.clone())
                            }
}

