// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`UpdateAccountStatus`](crate::operation::update_account_status::builders::UpdateAccountStatusFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::update_account_status::builders::UpdateAccountStatusFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::update_account_status::builders::UpdateAccountStatusFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`status(Status)`](crate::operation::update_account_status::builders::UpdateAccountStatusFluentBuilder::status) / [`set_status(Option<Status>)`](crate::operation::update_account_status::builders::UpdateAccountStatusFluentBuilder::set_status):<br>required: **true**<br>Account status.<br>
                            /// - On success, responds with [`UpdateAccountStatusOutput`](crate::operation::update_account_status::UpdateAccountStatusOutput) with field(s):
    ///   - [`id(String)`](crate::operation::update_account_status::UpdateAccountStatusOutput::id): (undocumented)
    ///   - [`holder_id(String)`](crate::operation::update_account_status::UpdateAccountStatusOutput::holder_id): (undocumented)
    ///   - [`purpose_code(String)`](crate::operation::update_account_status::UpdateAccountStatusOutput::purpose_code): (undocumented)
    ///   - [`origin_ifsc(String)`](crate::operation::update_account_status::UpdateAccountStatusOutput::origin_ifsc): (undocumented)
    ///   - [`origin_account_number(String)`](crate::operation::update_account_status::UpdateAccountStatusOutput::origin_account_number): (undocumented)
    ///   - [`vpa(Option<String>)`](crate::operation::update_account_status::UpdateAccountStatusOutput::vpa): (undocumented)
    ///   - [`virtual_ifsc(Option<String>)`](crate::operation::update_account_status::UpdateAccountStatusOutput::virtual_ifsc): (undocumented)
    ///   - [`virtual_account_number(Option<String>)`](crate::operation::update_account_status::UpdateAccountStatusOutput::virtual_account_number): (undocumented)
    ///   - [`kyc_tier(String)`](crate::operation::update_account_status::UpdateAccountStatusOutput::kyc_tier): (undocumented)
    ///   - [`status(String)`](crate::operation::update_account_status::UpdateAccountStatusOutput::status): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::update_account_status::UpdateAccountStatusOutput::created_at): ISO 8601 date-time.
    ///   - [`updated_at(DateTime)`](crate::operation::update_account_status::UpdateAccountStatusOutput::updated_at): ISO 8601 date-time.
                            /// - On failure, responds with [`SdkError<UpdateAccountStatusError>`](crate::operation::update_account_status::UpdateAccountStatusError)
    #[deprecated(note = "Use UpdatePBAccountStatus.", since = "2026-05-08")]
    pub fn update_account_status(&self) -> crate::operation::update_account_status::builders::UpdateAccountStatusFluentBuilder {
                                crate::operation::update_account_status::builders::UpdateAccountStatusFluentBuilder::new(self.handle.clone())
                            }
}

