// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`VoidNormalAccountDeposit`](crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`deposit_id(impl Into<String>)`](crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder::deposit_id) / [`set_deposit_id(Option<String>)`](crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder::set_deposit_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`reason(impl Into<String>)`](crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder::reason) / [`set_reason(Option<String>)`](crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder::set_reason):<br>required: **false**<br>Why the deposit was cancelled. Stored on the voided transaction as `void_reason`. Max 256 characters.<br>
                            /// - On success, responds with [`VoidNormalAccountDepositOutput`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositOutput) with field(s):
    ///   - [`deposit_id(String)`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositOutput::deposit_id): (undocumented)
    ///   - [`account_id(String)`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositOutput::account_id): (undocumented)
    ///   - [`amount(i64)`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositOutput::amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`status(String)`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositOutput::status): (undocumented)
    ///   - [`gateway_ref(Option<String>)`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositOutput::gateway_ref): (undocumented)
    ///   - [`timeout_seconds(Option<i32>)`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositOutput::timeout_seconds): (undocumented)
                            /// - On failure, responds with [`SdkError<VoidNormalAccountDepositError>`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositError)
    pub fn void_normal_account_deposit(&self) -> crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder {
                                crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositFluentBuilder::new(self.handle.clone())
                            }
}

