// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`VoidPBAccountContributionReturn`](crate::operation::void_pb_account_contribution_return::builders::VoidPBAccountContributionReturnFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`account_id(impl Into<String>)`](crate::operation::void_pb_account_contribution_return::builders::VoidPBAccountContributionReturnFluentBuilder::account_id) / [`set_account_id(Option<String>)`](crate::operation::void_pb_account_contribution_return::builders::VoidPBAccountContributionReturnFluentBuilder::set_account_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`return_id(impl Into<String>)`](crate::operation::void_pb_account_contribution_return::builders::VoidPBAccountContributionReturnFluentBuilder::return_id) / [`set_return_id(Option<String>)`](crate::operation::void_pb_account_contribution_return::builders::VoidPBAccountContributionReturnFluentBuilder::set_return_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`VoidPbAccountContributionReturnOutput`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput) with field(s):
    ///   - [`return_id(String)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::return_id): (undocumented)
    ///   - [`correlation_id(String)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::correlation_id): (undocumented)
    ///   - [`account_id(String)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::account_id): (undocumented)
    ///   - [`funding_type(FundingType)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::funding_type): Funding source type for deposits.
    ///   - [`amount(i64)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::amount): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`allocations(Vec::<AllocationEntry>)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::allocations): (undocumented)
    ///   - [`remaining_returnable_after(i64)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::remaining_returnable_after): Monetary amount in the smallest currency unit (e.g., paise for INR).
    ///   - [`status(TransactionStatus)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::status): Transaction status.
    ///   - [`created_at(DateTime)`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnOutput::created_at): ISO 8601 date-time.
                            /// - On failure, responds with [`SdkError<VoidPBAccountContributionReturnError>`](crate::operation::void_pb_account_contribution_return::VoidPBAccountContributionReturnError)
    pub fn void_pb_account_contribution_return(&self) -> crate::operation::void_pb_account_contribution_return::builders::VoidPBAccountContributionReturnFluentBuilder {
                                crate::operation::void_pb_account_contribution_return::builders::VoidPBAccountContributionReturnFluentBuilder::new(self.handle.clone())
                            }
}

