// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct VoidDepositInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub deposit_id: ::std::option::Option<::std::string::String>,
    /// Why the deposit was cancelled. Stored on the voided transaction as `void_reason`. Max 256 characters.
    pub reason: ::std::option::Option<::std::string::String>,
}
impl  VoidDepositInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn deposit_id(&self) -> ::std::option::Option<&str> {
        self.deposit_id.as_deref()
    }
    /// Why the deposit was cancelled. Stored on the voided transaction as `void_reason`. Max 256 characters.
    pub fn reason(&self) -> ::std::option::Option<&str> {
        self.reason.as_deref()
    }
}
impl VoidDepositInput {
    /// Creates a new builder-style object to manufacture [`VoidDepositInput`](crate::operation::void_deposit::VoidDepositInput).
    pub fn builder() -> crate::operation::void_deposit::builders::VoidDepositInputBuilder {
        crate::operation::void_deposit::builders::VoidDepositInputBuilder::default()
    }
}

/// A builder for [`VoidDepositInput`](crate::operation::void_deposit::VoidDepositInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct VoidDepositInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) deposit_id: ::std::option::Option<::std::string::String>,
    pub(crate) reason: ::std::option::Option<::std::string::String>,
}
impl VoidDepositInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn deposit_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.deposit_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_deposit_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.deposit_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_deposit_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.deposit_id
    }
    /// Why the deposit was cancelled. Stored on the voided transaction as `void_reason`. Max 256 characters.
    pub fn reason(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.reason = ::std::option::Option::Some(input.into());
        self
    }
    /// Why the deposit was cancelled. Stored on the voided transaction as `void_reason`. Max 256 characters.
    pub fn set_reason(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.reason = input; self
    }
    /// Why the deposit was cancelled. Stored on the voided transaction as `void_reason`. Max 256 characters.
    pub fn get_reason(&self) -> &::std::option::Option<::std::string::String> {
        &self.reason
    }
    /// Consumes the builder and constructs a [`VoidDepositInput`](crate::operation::void_deposit::VoidDepositInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::void_deposit::VoidDepositInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::void_deposit::VoidDepositInput {
                account_id: self.account_id
                ,
                deposit_id: self.deposit_id
                ,
                reason: self.reason
                ,
            }
        )
    }
}

