// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PostPbAccountRefundOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub refund_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub original_payment_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::string::String,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: i64,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount_to_self: i64,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount_to_others: i64,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub original_amount: i64,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub remaining_refundable: i64,
    #[allow(missing_docs)] // documentation missing in model
    pub status: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub correlation_id: ::std::string::String,
    /// ISO 8601 date-time.
    pub created_at: ::aws_smithy_types::DateTime,
}
impl  PostPbAccountRefundOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn refund_id(&self) -> &str {
        use std::ops::Deref; self.refund_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn original_payment_id(&self) -> &str {
        use std::ops::Deref; self.original_payment_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> &str {
        use std::ops::Deref; self.account_id.deref()
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> i64 {
        self.amount
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount_to_self(&self) -> i64 {
        self.amount_to_self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount_to_others(&self) -> i64 {
        self.amount_to_others
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn original_amount(&self) -> i64 {
        self.original_amount
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn remaining_refundable(&self) -> i64 {
        self.remaining_refundable
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> &str {
        use std::ops::Deref; self.status.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn correlation_id(&self) -> &str {
        use std::ops::Deref; self.correlation_id.deref()
    }
    /// ISO 8601 date-time.
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
}
impl PostPbAccountRefundOutput {
    /// Creates a new builder-style object to manufacture [`PostPbAccountRefundOutput`](crate::operation::post_pb_account_refund::PostPbAccountRefundOutput).
    pub fn builder() -> crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder {
        crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::default()
    }
}

/// A builder for [`PostPbAccountRefundOutput`](crate::operation::post_pb_account_refund::PostPbAccountRefundOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct PostPbAccountRefundOutputBuilder {
    pub(crate) refund_id: ::std::option::Option<::std::string::String>,
    pub(crate) original_payment_id: ::std::option::Option<::std::string::String>,
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) amount: ::std::option::Option<i64>,
    pub(crate) amount_to_self: ::std::option::Option<i64>,
    pub(crate) amount_to_others: ::std::option::Option<i64>,
    pub(crate) original_amount: ::std::option::Option<i64>,
    pub(crate) remaining_refundable: ::std::option::Option<i64>,
    pub(crate) status: ::std::option::Option<::std::string::String>,
    pub(crate) correlation_id: ::std::option::Option<::std::string::String>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl PostPbAccountRefundOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn refund_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.refund_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_refund_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.refund_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_refund_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.refund_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn original_payment_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.original_payment_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_original_payment_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.original_payment_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_original_payment_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.original_payment_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount_to_self(mut self, input: i64) -> Self {
        self.amount_to_self = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount_to_self(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount_to_self = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount_to_self(&self) -> &::std::option::Option<i64> {
        &self.amount_to_self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount_to_others(mut self, input: i64) -> Self {
        self.amount_to_others = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount_to_others(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount_to_others = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount_to_others(&self) -> &::std::option::Option<i64> {
        &self.amount_to_others
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn original_amount(mut self, input: i64) -> Self {
        self.original_amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_original_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.original_amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_original_amount(&self) -> &::std::option::Option<i64> {
        &self.original_amount
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn remaining_refundable(mut self, input: i64) -> Self {
        self.remaining_refundable = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_remaining_refundable(mut self, input: ::std::option::Option<i64>) -> Self {
        self.remaining_refundable = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_remaining_refundable(&self) -> &::std::option::Option<i64> {
        &self.remaining_refundable
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn status(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.status = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<::std::string::String> {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn correlation_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.correlation_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_correlation_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.correlation_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_correlation_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.correlation_id
    }
    /// ISO 8601 date-time.
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    /// ISO 8601 date-time.
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input; self
    }
    /// ISO 8601 date-time.
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    /// Consumes the builder and constructs a [`PostPbAccountRefundOutput`](crate::operation::post_pb_account_refund::PostPbAccountRefundOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`refund_id`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::refund_id)
    /// - [`original_payment_id`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::original_payment_id)
    /// - [`account_id`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::account_id)
    /// - [`amount`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::amount)
    /// - [`amount_to_self`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::amount_to_self)
    /// - [`amount_to_others`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::amount_to_others)
    /// - [`original_amount`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::original_amount)
    /// - [`remaining_refundable`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::remaining_refundable)
    /// - [`status`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::status)
    /// - [`correlation_id`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::correlation_id)
    /// - [`created_at`](crate::operation::post_pb_account_refund::builders::PostPbAccountRefundOutputBuilder::created_at)
    pub fn build(self) -> ::std::result::Result<crate::operation::post_pb_account_refund::PostPbAccountRefundOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::post_pb_account_refund::PostPbAccountRefundOutput {
                refund_id: self.refund_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("refund_id", "refund_id was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                original_payment_id: self.original_payment_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("original_payment_id", "original_payment_id was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                account_id: self.account_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("account_id", "account_id was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                amount: self.amount
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("amount", "amount was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                amount_to_self: self.amount_to_self
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("amount_to_self", "amount_to_self was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                amount_to_others: self.amount_to_others
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("amount_to_others", "amount_to_others was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                original_amount: self.original_amount
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("original_amount", "original_amount was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                remaining_refundable: self.remaining_refundable
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("remaining_refundable", "remaining_refundable was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                status: self.status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("status", "status was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                correlation_id: self.correlation_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("correlation_id", "correlation_id was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
                created_at: self.created_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("created_at", "created_at was not specified but it is required when building PostPbAccountRefundOutput")
                    )?
                ,
            }
        )
    }
}

