// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct VoidPbAccountDepositOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub deposit_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::string::String,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: i64,
    #[allow(missing_docs)] // documentation missing in model
    pub pool: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub funding_type: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub status: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub gateway_ref: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub timeout_seconds: ::std::option::Option<i32>,
}
impl  VoidPbAccountDepositOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn deposit_id(&self) -> &str {
        use std::ops::Deref; self.deposit_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> &str {
        use std::ops::Deref; self.account_id.deref()
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> i64 {
        self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn pool(&self) -> &str {
        use std::ops::Deref; self.pool.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn funding_type(&self) -> ::std::option::Option<&str> {
        self.funding_type.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> &str {
        use std::ops::Deref; self.status.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(&self) -> ::std::option::Option<&str> {
        self.gateway_ref.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn timeout_seconds(&self) -> ::std::option::Option<i32> {
        self.timeout_seconds
    }
}
impl VoidPbAccountDepositOutput {
    /// Creates a new builder-style object to manufacture [`VoidPbAccountDepositOutput`](crate::operation::void_pb_account_deposit::VoidPbAccountDepositOutput).
    pub fn builder() -> crate::operation::void_pb_account_deposit::builders::VoidPbAccountDepositOutputBuilder {
        crate::operation::void_pb_account_deposit::builders::VoidPbAccountDepositOutputBuilder::default()
    }
}

/// A builder for [`VoidPbAccountDepositOutput`](crate::operation::void_pb_account_deposit::VoidPbAccountDepositOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct VoidPbAccountDepositOutputBuilder {
    pub(crate) deposit_id: ::std::option::Option<::std::string::String>,
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) amount: ::std::option::Option<i64>,
    pub(crate) pool: ::std::option::Option<::std::string::String>,
    pub(crate) funding_type: ::std::option::Option<::std::string::String>,
    pub(crate) status: ::std::option::Option<::std::string::String>,
    pub(crate) gateway_ref: ::std::option::Option<::std::string::String>,
    pub(crate) timeout_seconds: ::std::option::Option<i32>,
}
impl VoidPbAccountDepositOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn deposit_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.deposit_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_deposit_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.deposit_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_deposit_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.deposit_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn pool(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.pool = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_pool(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.pool = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_pool(&self) -> &::std::option::Option<::std::string::String> {
        &self.pool
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn funding_type(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.funding_type = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_funding_type(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.funding_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_funding_type(&self) -> &::std::option::Option<::std::string::String> {
        &self.funding_type
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn status(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.status = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<::std::string::String> {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.gateway_ref = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_gateway_ref(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.gateway_ref = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_gateway_ref(&self) -> &::std::option::Option<::std::string::String> {
        &self.gateway_ref
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn timeout_seconds(mut self, input: i32) -> Self {
        self.timeout_seconds = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_timeout_seconds(mut self, input: ::std::option::Option<i32>) -> Self {
        self.timeout_seconds = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_timeout_seconds(&self) -> &::std::option::Option<i32> {
        &self.timeout_seconds
    }
    /// Consumes the builder and constructs a [`VoidPbAccountDepositOutput`](crate::operation::void_pb_account_deposit::VoidPbAccountDepositOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`deposit_id`](crate::operation::void_pb_account_deposit::builders::VoidPbAccountDepositOutputBuilder::deposit_id)
    /// - [`account_id`](crate::operation::void_pb_account_deposit::builders::VoidPbAccountDepositOutputBuilder::account_id)
    /// - [`amount`](crate::operation::void_pb_account_deposit::builders::VoidPbAccountDepositOutputBuilder::amount)
    /// - [`pool`](crate::operation::void_pb_account_deposit::builders::VoidPbAccountDepositOutputBuilder::pool)
    /// - [`status`](crate::operation::void_pb_account_deposit::builders::VoidPbAccountDepositOutputBuilder::status)
    pub fn build(self) -> ::std::result::Result<crate::operation::void_pb_account_deposit::VoidPbAccountDepositOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::void_pb_account_deposit::VoidPbAccountDepositOutput {
                deposit_id: self.deposit_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("deposit_id", "deposit_id was not specified but it is required when building VoidPbAccountDepositOutput")
                    )?
                ,
                account_id: self.account_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("account_id", "account_id was not specified but it is required when building VoidPbAccountDepositOutput")
                    )?
                ,
                amount: self.amount
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("amount", "amount was not specified but it is required when building VoidPbAccountDepositOutput")
                    )?
                ,
                pool: self.pool
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("pool", "pool was not specified but it is required when building VoidPbAccountDepositOutput")
                    )?
                ,
                funding_type: self.funding_type
                ,
                status: self.status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("status", "status was not specified but it is required when building VoidPbAccountDepositOutput")
                    )?
                ,
                gateway_ref: self.gateway_ref
                ,
                timeout_seconds: self.timeout_seconds
                ,
            }
        )
    }
}

