// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DepositOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::string::String,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: i64,
    #[allow(missing_docs)] // documentation missing in model
    pub pool: ::std::string::String,
}
impl DepositOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> &str {
        use std::ops::Deref;
        self.account_id.deref()
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> i64 {
        self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn pool(&self) -> &str {
        use std::ops::Deref;
        self.pool.deref()
    }
}
impl DepositOutput {
    /// Creates a new builder-style object to manufacture [`DepositOutput`](crate::operation::deposit::DepositOutput).
    pub fn builder() -> crate::operation::deposit::builders::DepositOutputBuilder {
        crate::operation::deposit::builders::DepositOutputBuilder::default()
    }
}

/// A builder for [`DepositOutput`](crate::operation::deposit::DepositOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DepositOutputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) amount: ::std::option::Option<i64>,
    pub(crate) pool: ::std::option::Option<::std::string::String>,
}
impl DepositOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input;
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn pool(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.pool = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_pool(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.pool = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_pool(&self) -> &::std::option::Option<::std::string::String> {
        &self.pool
    }
    /// Consumes the builder and constructs a [`DepositOutput`](crate::operation::deposit::DepositOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`account_id`](crate::operation::deposit::builders::DepositOutputBuilder::account_id)
    /// - [`amount`](crate::operation::deposit::builders::DepositOutputBuilder::amount)
    /// - [`pool`](crate::operation::deposit::builders::DepositOutputBuilder::pool)
    pub fn build(self) -> ::std::result::Result<crate::operation::deposit::DepositOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::deposit::DepositOutput {
            account_id: self.account_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "account_id",
                    "account_id was not specified but it is required when building DepositOutput",
                )
            })?,
            amount: self.amount.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "amount",
                    "amount was not specified but it is required when building DepositOutput",
                )
            })?,
            pool: self.pool.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "pool",
                    "pool was not specified but it is required when building DepositOutput",
                )
            })?,
        })
    }
}
