// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::get_pb_account_contribution_summary::_get_pb_account_contribution_summary_output::GetPbAccountContributionSummaryOutputBuilder;

pub use crate::operation::get_pb_account_contribution_summary::_get_pb_account_contribution_summary_input::GetPbAccountContributionSummaryInputBuilder;

impl crate::operation::get_pb_account_contribution_summary::builders::GetPbAccountContributionSummaryInputBuilder {
                    /// Sends a request with this input using the given client.
                    pub async fn send_with(self, client: &crate::Client) -> ::std::result::Result<
                        crate::operation::get_pb_account_contribution_summary::GetPbAccountContributionSummaryOutput,
                        ::aws_smithy_runtime_api::client::result::SdkError<
                            crate::operation::get_pb_account_contribution_summary::GetPBAccountContributionSummaryError,
                            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse
                        >
                    > {
                        let mut fluent_builder = client.get_pb_account_contribution_summary();
                        fluent_builder.inner = self;
                        fluent_builder.send().await
                    }
                }
/// Fluent builder constructing a request to `GetPBAccountContributionSummary`.
/// 
/// Get a summary of contributions and returns per funding type.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct GetPBAccountContributionSummaryFluentBuilder {
                handle: ::std::sync::Arc<crate::client::Handle>,
                inner: crate::operation::get_pb_account_contribution_summary::builders::GetPbAccountContributionSummaryInputBuilder,
config_override: ::std::option::Option<crate::config::Builder>,
            }
impl
                crate::client::customize::internal::CustomizableSend<
                    crate::operation::get_pb_account_contribution_summary::GetPbAccountContributionSummaryOutput,
                    crate::operation::get_pb_account_contribution_summary::GetPBAccountContributionSummaryError,
                > for GetPBAccountContributionSummaryFluentBuilder
            {
                fn send(
                    self,
                    config_override: crate::config::Builder,
                ) -> crate::client::customize::internal::BoxFuture<
                    crate::client::customize::internal::SendResult<
                        crate::operation::get_pb_account_contribution_summary::GetPbAccountContributionSummaryOutput,
                        crate::operation::get_pb_account_contribution_summary::GetPBAccountContributionSummaryError,
                    >,
                > {
                    ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
                }
            }
impl GetPBAccountContributionSummaryFluentBuilder {
    /// Creates a new `GetPBAccountContributionSummaryFluentBuilder`.
                    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
                        Self {
                            handle,
                            inner: ::std::default::Default::default(),
    config_override: ::std::option::Option::None,
                        }
                    }
    /// Access the GetPBAccountContributionSummary as a reference.
                    pub fn as_input(&self) -> &crate::operation::get_pb_account_contribution_summary::builders::GetPbAccountContributionSummaryInputBuilder {
                        &self.inner
                    }
    /// Sends the request and returns the response.
                    ///
                    /// If an error occurs, an `SdkError` will be returned with additional details that
                    /// can be matched against.
                    ///
                    /// By default, any retryable failures will be retried twice. Retry behavior
                    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
                    /// set when configuring the client.
                    pub async fn send(self) -> ::std::result::Result<crate::operation::get_pb_account_contribution_summary::GetPbAccountContributionSummaryOutput, ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_pb_account_contribution_summary::GetPBAccountContributionSummaryError, ::aws_smithy_runtime_api::client::orchestrator::HttpResponse>> {
                        let input = self.inner.build().map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
                        let runtime_plugins = crate::operation::get_pb_account_contribution_summary::GetPBAccountContributionSummary::operation_runtime_plugins(
                            self.handle.runtime_plugins.clone(),
                            &self.handle.conf,
                            self.config_override,
                        );
                        crate::operation::get_pb_account_contribution_summary::GetPBAccountContributionSummary::orchestrate(&runtime_plugins, input).await
                    }
    
                    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
                    pub fn customize(
                        self,
                    ) -> crate::client::customize::CustomizableOperation<crate::operation::get_pb_account_contribution_summary::GetPbAccountContributionSummaryOutput, crate::operation::get_pb_account_contribution_summary::GetPBAccountContributionSummaryError, Self> {
                        crate::client::customize::CustomizableOperation::new(self)
                    }
    pub(crate) fn config_override(
                            mut self,
                            config_override: impl ::std::convert::Into<crate::config::Builder>,
                        ) -> Self {
                            self.set_config_override(::std::option::Option::Some(config_override.into()));
                            self
                        }
    
                        pub(crate) fn set_config_override(
                            &mut self,
                            config_override: ::std::option::Option<crate::config::Builder>,
                        ) -> &mut Self {
                            self.config_override = config_override;
                            self
                        }
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.account_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_account_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_account_id()
                }
}

