// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::list_all_transactions::_list_all_transactions_output::ListAllTransactionsOutputBuilder;

pub use crate::operation::list_all_transactions::_list_all_transactions_input::ListAllTransactionsInputBuilder;

impl crate::operation::list_all_transactions::builders::ListAllTransactionsInputBuilder {
                    /// Sends a request with this input using the given client.
                    pub async fn send_with(self, client: &crate::Client) -> ::std::result::Result<
                        crate::operation::list_all_transactions::ListAllTransactionsOutput,
                        ::aws_smithy_runtime_api::client::result::SdkError<
                            crate::operation::list_all_transactions::ListAllTransactionsError,
                            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse
                        >
                    > {
                        let mut fluent_builder = client.list_all_transactions();
                        fluent_builder.inner = self;
                        fluent_builder.send().await
                    }
                }
/// Fluent builder constructing a request to `ListAllTransactions`.
/// 
/// List all transactions across all accounts with offset/limit pagination.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct ListAllTransactionsFluentBuilder {
                handle: ::std::sync::Arc<crate::client::Handle>,
                inner: crate::operation::list_all_transactions::builders::ListAllTransactionsInputBuilder,
config_override: ::std::option::Option<crate::config::Builder>,
            }
impl
                crate::client::customize::internal::CustomizableSend<
                    crate::operation::list_all_transactions::ListAllTransactionsOutput,
                    crate::operation::list_all_transactions::ListAllTransactionsError,
                > for ListAllTransactionsFluentBuilder
            {
                fn send(
                    self,
                    config_override: crate::config::Builder,
                ) -> crate::client::customize::internal::BoxFuture<
                    crate::client::customize::internal::SendResult<
                        crate::operation::list_all_transactions::ListAllTransactionsOutput,
                        crate::operation::list_all_transactions::ListAllTransactionsError,
                    >,
                > {
                    ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
                }
            }
impl ListAllTransactionsFluentBuilder {
    /// Creates a new `ListAllTransactionsFluentBuilder`.
                    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
                        Self {
                            handle,
                            inner: ::std::default::Default::default(),
    config_override: ::std::option::Option::None,
                        }
                    }
    /// Access the ListAllTransactions as a reference.
                    pub fn as_input(&self) -> &crate::operation::list_all_transactions::builders::ListAllTransactionsInputBuilder {
                        &self.inner
                    }
    /// Sends the request and returns the response.
                    ///
                    /// If an error occurs, an `SdkError` will be returned with additional details that
                    /// can be matched against.
                    ///
                    /// By default, any retryable failures will be retried twice. Retry behavior
                    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
                    /// set when configuring the client.
                    pub async fn send(self) -> ::std::result::Result<crate::operation::list_all_transactions::ListAllTransactionsOutput, ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::list_all_transactions::ListAllTransactionsError, ::aws_smithy_runtime_api::client::orchestrator::HttpResponse>> {
                        let input = self.inner.build().map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
                        let runtime_plugins = crate::operation::list_all_transactions::ListAllTransactions::operation_runtime_plugins(
                            self.handle.runtime_plugins.clone(),
                            &self.handle.conf,
                            self.config_override,
                        );
                        crate::operation::list_all_transactions::ListAllTransactions::orchestrate(&runtime_plugins, input).await
                    }
    
                    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
                    pub fn customize(
                        self,
                    ) -> crate::client::customize::CustomizableOperation<crate::operation::list_all_transactions::ListAllTransactionsOutput, crate::operation::list_all_transactions::ListAllTransactionsError, Self> {
                        crate::client::customize::CustomizableOperation::new(self)
                    }
    pub(crate) fn config_override(
                            mut self,
                            config_override: impl ::std::convert::Into<crate::config::Builder>,
                        ) -> Self {
                            self.set_config_override(::std::option::Option::Some(config_override.into()));
                            self
                        }
    
                        pub(crate) fn set_config_override(
                            &mut self,
                            config_override: ::std::option::Option<crate::config::Builder>,
                        ) -> &mut Self {
                            self.config_override = config_override;
                            self
                        }
    #[allow(missing_docs)] // documentation missing in model
    pub fn offset(mut self, input: i64) -> Self {
                    self.inner = self.inner.offset(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_offset(mut self, input: ::std::option::Option<i64>) -> Self {
                    self.inner = self.inner.set_offset(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_offset(&self) -> &::std::option::Option<i64> {
                    self.inner.get_offset()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(mut self, input: i64) -> Self {
                    self.inner = self.inner.limit(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_limit(mut self, input: ::std::option::Option<i64>) -> Self {
                    self.inner = self.inner.set_limit(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_limit(&self) -> &::std::option::Option<i64> {
                    self.inner.get_limit()
                }
    /// ISO 8601 date-time.
    pub fn from_date(mut self, input: ::aws_smithy_types::DateTime) -> Self {
                    self.inner = self.inner.from_date(input);
                    self
                }
    /// ISO 8601 date-time.
    pub fn set_from_date(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
                    self.inner = self.inner.set_from_date(input);
                    self
                }
    /// ISO 8601 date-time.
    pub fn get_from_date(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
                    self.inner.get_from_date()
                }
    /// ISO 8601 date-time.
    pub fn to_date(mut self, input: ::aws_smithy_types::DateTime) -> Self {
                    self.inner = self.inner.to_date(input);
                    self
                }
    /// ISO 8601 date-time.
    pub fn set_to_date(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
                    self.inner = self.inner.set_to_date(input);
                    self
                }
    /// ISO 8601 date-time.
    pub fn get_to_date(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
                    self.inner.get_to_date()
                }
}

