// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DepositToNormalAccountInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: ::std::option::Option<i64>,
    #[allow(missing_docs)] // documentation missing in model
    pub pending: ::std::option::Option<bool>,
    #[allow(missing_docs)] // documentation missing in model
    pub gateway_ref: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub timeout_seconds: ::std::option::Option<i32>,
    /// Free-text narration for the deposit, stored on the transaction and returned by the transaction listings. Max 256 characters.
    pub description: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub idempotency_key: ::std::option::Option<::std::string::String>,
}
impl  DepositToNormalAccountInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> ::std::option::Option<i64> {
        self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn pending(&self) -> ::std::option::Option<bool> {
        self.pending
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(&self) -> ::std::option::Option<&str> {
        self.gateway_ref.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn timeout_seconds(&self) -> ::std::option::Option<i32> {
        self.timeout_seconds
    }
    /// Free-text narration for the deposit, stored on the transaction and returned by the transaction listings. Max 256 characters.
    pub fn description(&self) -> ::std::option::Option<&str> {
        self.description.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(&self) -> ::std::option::Option<&str> {
        self.idempotency_key.as_deref()
    }
}
impl DepositToNormalAccountInput {
    /// Creates a new builder-style object to manufacture [`DepositToNormalAccountInput`](crate::operation::deposit_to_normal_account::DepositToNormalAccountInput).
    pub fn builder() -> crate::operation::deposit_to_normal_account::builders::DepositToNormalAccountInputBuilder {
        crate::operation::deposit_to_normal_account::builders::DepositToNormalAccountInputBuilder::default()
    }
}

/// A builder for [`DepositToNormalAccountInput`](crate::operation::deposit_to_normal_account::DepositToNormalAccountInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DepositToNormalAccountInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) amount: ::std::option::Option<i64>,
    pub(crate) pending: ::std::option::Option<bool>,
    pub(crate) gateway_ref: ::std::option::Option<::std::string::String>,
    pub(crate) timeout_seconds: ::std::option::Option<i32>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) idempotency_key: ::std::option::Option<::std::string::String>,
}
impl DepositToNormalAccountInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn pending(mut self, input: bool) -> Self {
        self.pending = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_pending(mut self, input: ::std::option::Option<bool>) -> Self {
        self.pending = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_pending(&self) -> &::std::option::Option<bool> {
        &self.pending
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.gateway_ref = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_gateway_ref(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.gateway_ref = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_gateway_ref(&self) -> &::std::option::Option<::std::string::String> {
        &self.gateway_ref
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn timeout_seconds(mut self, input: i32) -> Self {
        self.timeout_seconds = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_timeout_seconds(mut self, input: ::std::option::Option<i32>) -> Self {
        self.timeout_seconds = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_timeout_seconds(&self) -> &::std::option::Option<i32> {
        &self.timeout_seconds
    }
    /// Free-text narration for the deposit, stored on the transaction and returned by the transaction listings. Max 256 characters.
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    /// Free-text narration for the deposit, stored on the transaction and returned by the transaction listings. Max 256 characters.
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input; self
    }
    /// Free-text narration for the deposit, stored on the transaction and returned by the transaction listings. Max 256 characters.
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idempotency_key = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_idempotency_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idempotency_key = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_idempotency_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.idempotency_key
    }
    /// Consumes the builder and constructs a [`DepositToNormalAccountInput`](crate::operation::deposit_to_normal_account::DepositToNormalAccountInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::deposit_to_normal_account::DepositToNormalAccountInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::deposit_to_normal_account::DepositToNormalAccountInput {
                account_id: self.account_id
                ,
                amount: self.amount
                ,
                pending: self.pending
                ,
                gateway_ref: self.gateway_ref
                ,
                timeout_seconds: self.timeout_seconds
                ,
                description: self.description
                ,
                idempotency_key: self.idempotency_key
                ,
            }
        )
    }
}

