// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListNormalAccountsInput  {
}
impl ListNormalAccountsInput {
    /// Creates a new builder-style object to manufacture [`ListNormalAccountsInput`](crate::operation::list_normal_accounts::ListNormalAccountsInput).
    pub fn builder() -> crate::operation::list_normal_accounts::builders::ListNormalAccountsInputBuilder {
        crate::operation::list_normal_accounts::builders::ListNormalAccountsInputBuilder::default()
    }
}

/// A builder for [`ListNormalAccountsInput`](crate::operation::list_normal_accounts::ListNormalAccountsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListNormalAccountsInputBuilder {
}
impl ListNormalAccountsInputBuilder {
    /// Consumes the builder and constructs a [`ListNormalAccountsInput`](crate::operation::list_normal_accounts::ListNormalAccountsInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::list_normal_accounts::ListNormalAccountsInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::list_normal_accounts::ListNormalAccountsInput {
            }
        )
    }
}

