// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Shared account fields.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetPbAccountOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub holder_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub purpose_code: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub origin_ifsc: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub origin_account_number: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub vpa: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub virtual_ifsc: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub virtual_account_number: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub kyc_tier: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub status: ::std::string::String,
    /// ISO 8601 date-time.
    pub created_at: ::aws_smithy_types::DateTime,
    /// ISO 8601 date-time.
    pub updated_at: ::aws_smithy_types::DateTime,
}
impl  GetPbAccountOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn id(&self) -> &str {
        use std::ops::Deref; self.id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn holder_id(&self) -> &str {
        use std::ops::Deref; self.holder_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn purpose_code(&self) -> &str {
        use std::ops::Deref; self.purpose_code.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn origin_ifsc(&self) -> &str {
        use std::ops::Deref; self.origin_ifsc.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn origin_account_number(&self) -> &str {
        use std::ops::Deref; self.origin_account_number.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn vpa(&self) -> ::std::option::Option<&str> {
        self.vpa.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn virtual_ifsc(&self) -> ::std::option::Option<&str> {
        self.virtual_ifsc.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn virtual_account_number(&self) -> ::std::option::Option<&str> {
        self.virtual_account_number.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn kyc_tier(&self) -> &str {
        use std::ops::Deref; self.kyc_tier.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> &str {
        use std::ops::Deref; self.status.deref()
    }
    /// ISO 8601 date-time.
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
    /// ISO 8601 date-time.
    pub fn updated_at(&self) -> &::aws_smithy_types::DateTime {
        &self.updated_at
    }
}
impl GetPbAccountOutput {
    /// Creates a new builder-style object to manufacture [`GetPbAccountOutput`](crate::operation::get_pb_account::GetPbAccountOutput).
    pub fn builder() -> crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder {
        crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::default()
    }
}

/// A builder for [`GetPbAccountOutput`](crate::operation::get_pb_account::GetPbAccountOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetPbAccountOutputBuilder {
    pub(crate) id: ::std::option::Option<::std::string::String>,
    pub(crate) holder_id: ::std::option::Option<::std::string::String>,
    pub(crate) purpose_code: ::std::option::Option<::std::string::String>,
    pub(crate) origin_ifsc: ::std::option::Option<::std::string::String>,
    pub(crate) origin_account_number: ::std::option::Option<::std::string::String>,
    pub(crate) vpa: ::std::option::Option<::std::string::String>,
    pub(crate) virtual_ifsc: ::std::option::Option<::std::string::String>,
    pub(crate) virtual_account_number: ::std::option::Option<::std::string::String>,
    pub(crate) kyc_tier: ::std::option::Option<::std::string::String>,
    pub(crate) status: ::std::option::Option<::std::string::String>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) updated_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl GetPbAccountOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn holder_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.holder_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_holder_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.holder_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_holder_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.holder_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn purpose_code(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.purpose_code = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_purpose_code(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.purpose_code = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_purpose_code(&self) -> &::std::option::Option<::std::string::String> {
        &self.purpose_code
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn origin_ifsc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.origin_ifsc = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_origin_ifsc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.origin_ifsc = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_origin_ifsc(&self) -> &::std::option::Option<::std::string::String> {
        &self.origin_ifsc
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn origin_account_number(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.origin_account_number = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_origin_account_number(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.origin_account_number = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_origin_account_number(&self) -> &::std::option::Option<::std::string::String> {
        &self.origin_account_number
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn vpa(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.vpa = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_vpa(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.vpa = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_vpa(&self) -> &::std::option::Option<::std::string::String> {
        &self.vpa
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn virtual_ifsc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.virtual_ifsc = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_virtual_ifsc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.virtual_ifsc = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_virtual_ifsc(&self) -> &::std::option::Option<::std::string::String> {
        &self.virtual_ifsc
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn virtual_account_number(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.virtual_account_number = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_virtual_account_number(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.virtual_account_number = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_virtual_account_number(&self) -> &::std::option::Option<::std::string::String> {
        &self.virtual_account_number
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn kyc_tier(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.kyc_tier = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_kyc_tier(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.kyc_tier = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_kyc_tier(&self) -> &::std::option::Option<::std::string::String> {
        &self.kyc_tier
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn status(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.status = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<::std::string::String> {
        &self.status
    }
    /// ISO 8601 date-time.
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    /// ISO 8601 date-time.
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input; self
    }
    /// ISO 8601 date-time.
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    /// ISO 8601 date-time.
    /// This field is required.
    pub fn updated_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.updated_at = ::std::option::Option::Some(input);
        self
    }
    /// ISO 8601 date-time.
    pub fn set_updated_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.updated_at = input; self
    }
    /// ISO 8601 date-time.
    pub fn get_updated_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.updated_at
    }
    /// Consumes the builder and constructs a [`GetPbAccountOutput`](crate::operation::get_pb_account::GetPbAccountOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`id`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::id)
    /// - [`holder_id`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::holder_id)
    /// - [`purpose_code`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::purpose_code)
    /// - [`origin_ifsc`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::origin_ifsc)
    /// - [`origin_account_number`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::origin_account_number)
    /// - [`kyc_tier`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::kyc_tier)
    /// - [`status`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::status)
    /// - [`created_at`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::created_at)
    /// - [`updated_at`](crate::operation::get_pb_account::builders::GetPbAccountOutputBuilder::updated_at)
    pub fn build(self) -> ::std::result::Result<crate::operation::get_pb_account::GetPbAccountOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::get_pb_account::GetPbAccountOutput {
                id: self.id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("id", "id was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
                holder_id: self.holder_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("holder_id", "holder_id was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
                purpose_code: self.purpose_code
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("purpose_code", "purpose_code was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
                origin_ifsc: self.origin_ifsc
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("origin_ifsc", "origin_ifsc was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
                origin_account_number: self.origin_account_number
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("origin_account_number", "origin_account_number was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
                vpa: self.vpa
                ,
                virtual_ifsc: self.virtual_ifsc
                ,
                virtual_account_number: self.virtual_account_number
                ,
                kyc_tier: self.kyc_tier
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("kyc_tier", "kyc_tier was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
                status: self.status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("status", "status was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
                created_at: self.created_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("created_at", "created_at was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
                updated_at: self.updated_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("updated_at", "updated_at was not specified but it is required when building GetPbAccountOutput")
                    )?
                ,
            }
        )
    }
}

