// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::refund_pb_account_payment::_refund_pb_account_payment_output::RefundPbAccountPaymentOutputBuilder;

pub use crate::operation::refund_pb_account_payment::_refund_pb_account_payment_input::RefundPbAccountPaymentInputBuilder;

impl crate::operation::refund_pb_account_payment::builders::RefundPbAccountPaymentInputBuilder {
                    /// Sends a request with this input using the given client.
                    pub async fn send_with(self, client: &crate::Client) -> ::std::result::Result<
                        crate::operation::refund_pb_account_payment::RefundPbAccountPaymentOutput,
                        ::aws_smithy_runtime_api::client::result::SdkError<
                            crate::operation::refund_pb_account_payment::RefundPBAccountPaymentError,
                            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse
                        >
                    > {
                        let mut fluent_builder = client.refund_pb_account_payment();
                        fluent_builder.inner = self;
                        fluent_builder.send().await
                    }
                }
/// Fluent builder constructing a request to `RefundPBAccountPayment`.
/// 
/// Refund a previously settled PB→merchant payment. Records a new compensating transaction (1 or 2 rows mirroring the payment's pool split) plus matching TB transfer(s) in the opposite direction. Original payment rows are not mutated; each refund row links back via `reverses_transaction_id`. Multiple partial refunds are allowed per payment; the sum must not exceed the original payment amount. Refund credits self-pool first up to that pool's remaining-unrefunded amount, then others-pool. The PB account must be Active. Refunds cannot themselves be refunded.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct RefundPBAccountPaymentFluentBuilder {
                handle: ::std::sync::Arc<crate::client::Handle>,
                inner: crate::operation::refund_pb_account_payment::builders::RefundPbAccountPaymentInputBuilder,
config_override: ::std::option::Option<crate::config::Builder>,
            }
impl
                crate::client::customize::internal::CustomizableSend<
                    crate::operation::refund_pb_account_payment::RefundPbAccountPaymentOutput,
                    crate::operation::refund_pb_account_payment::RefundPBAccountPaymentError,
                > for RefundPBAccountPaymentFluentBuilder
            {
                fn send(
                    self,
                    config_override: crate::config::Builder,
                ) -> crate::client::customize::internal::BoxFuture<
                    crate::client::customize::internal::SendResult<
                        crate::operation::refund_pb_account_payment::RefundPbAccountPaymentOutput,
                        crate::operation::refund_pb_account_payment::RefundPBAccountPaymentError,
                    >,
                > {
                    ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
                }
            }
impl RefundPBAccountPaymentFluentBuilder {
    /// Creates a new `RefundPBAccountPaymentFluentBuilder`.
                    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
                        Self {
                            handle,
                            inner: ::std::default::Default::default(),
    config_override: ::std::option::Option::None,
                        }
                    }
    /// Access the RefundPBAccountPayment as a reference.
                    pub fn as_input(&self) -> &crate::operation::refund_pb_account_payment::builders::RefundPbAccountPaymentInputBuilder {
                        &self.inner
                    }
    /// Sends the request and returns the response.
                    ///
                    /// If an error occurs, an `SdkError` will be returned with additional details that
                    /// can be matched against.
                    ///
                    /// By default, any retryable failures will be retried twice. Retry behavior
                    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
                    /// set when configuring the client.
                    pub async fn send(self) -> ::std::result::Result<crate::operation::refund_pb_account_payment::RefundPbAccountPaymentOutput, ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::refund_pb_account_payment::RefundPBAccountPaymentError, ::aws_smithy_runtime_api::client::orchestrator::HttpResponse>> {
                        let input = self.inner.build().map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
                        let runtime_plugins = crate::operation::refund_pb_account_payment::RefundPBAccountPayment::operation_runtime_plugins(
                            self.handle.runtime_plugins.clone(),
                            &self.handle.conf,
                            self.config_override,
                        );
                        crate::operation::refund_pb_account_payment::RefundPBAccountPayment::orchestrate(&runtime_plugins, input).await
                    }
    
                    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
                    pub fn customize(
                        self,
                    ) -> crate::client::customize::CustomizableOperation<crate::operation::refund_pb_account_payment::RefundPbAccountPaymentOutput, crate::operation::refund_pb_account_payment::RefundPBAccountPaymentError, Self> {
                        crate::client::customize::CustomizableOperation::new(self)
                    }
    pub(crate) fn config_override(
                            mut self,
                            config_override: impl ::std::convert::Into<crate::config::Builder>,
                        ) -> Self {
                            self.set_config_override(::std::option::Option::Some(config_override.into()));
                            self
                        }
    
                        pub(crate) fn set_config_override(
                            &mut self,
                            config_override: ::std::option::Option<crate::config::Builder>,
                        ) -> &mut Self {
                            self.config_override = config_override;
                            self
                        }
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.account_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_account_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_account_id()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn payment_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.payment_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_payment_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_payment_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_payment_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_payment_id()
                }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(mut self, input: i64) -> Self {
                    self.inner = self.inner.amount(input);
                    self
                }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
                    self.inner = self.inner.set_amount(input);
                    self
                }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
                    self.inner.get_amount()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.description(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_description(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_description()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.gateway_ref(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_gateway_ref(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_gateway_ref(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_gateway_ref(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_gateway_ref()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.idempotency_key(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_idempotency_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_idempotency_key(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_idempotency_key(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_idempotency_key()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn pending(mut self, input: bool) -> Self {
                    self.inner = self.inner.pending(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_pending(mut self, input: ::std::option::Option<bool>) -> Self {
                    self.inner = self.inner.set_pending(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_pending(&self) -> &::std::option::Option<bool> {
                    self.inner.get_pending()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn timeout_seconds(mut self, input: i32) -> Self {
                    self.inner = self.inner.timeout_seconds(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_timeout_seconds(mut self, input: ::std::option::Option<i32>) -> Self {
                    self.inner = self.inner.set_timeout_seconds(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_timeout_seconds(&self) -> &::std::option::Option<i32> {
                    self.inner.get_timeout_seconds()
                }
}

