// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct VoidNormalAccountDepositInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub deposit_id: ::std::option::Option<::std::string::String>,
}
impl  VoidNormalAccountDepositInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn deposit_id(&self) -> ::std::option::Option<&str> {
        self.deposit_id.as_deref()
    }
}
impl VoidNormalAccountDepositInput {
    /// Creates a new builder-style object to manufacture [`VoidNormalAccountDepositInput`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositInput).
    pub fn builder() -> crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositInputBuilder {
        crate::operation::void_normal_account_deposit::builders::VoidNormalAccountDepositInputBuilder::default()
    }
}

/// A builder for [`VoidNormalAccountDepositInput`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct VoidNormalAccountDepositInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) deposit_id: ::std::option::Option<::std::string::String>,
}
impl VoidNormalAccountDepositInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn deposit_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.deposit_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_deposit_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.deposit_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_deposit_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.deposit_id
    }
    /// Consumes the builder and constructs a [`VoidNormalAccountDepositInput`](crate::operation::void_normal_account_deposit::VoidNormalAccountDepositInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::void_normal_account_deposit::VoidNormalAccountDepositInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::void_normal_account_deposit::VoidNormalAccountDepositInput {
                account_id: self.account_id
                ,
                deposit_id: self.deposit_id
                ,
            }
        )
    }
}

