// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetPbAccountBalanceInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
}
impl  GetPbAccountBalanceInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
}
impl GetPbAccountBalanceInput {
    /// Creates a new builder-style object to manufacture [`GetPbAccountBalanceInput`](crate::operation::get_pb_account_balance::GetPbAccountBalanceInput).
    pub fn builder() -> crate::operation::get_pb_account_balance::builders::GetPbAccountBalanceInputBuilder {
        crate::operation::get_pb_account_balance::builders::GetPbAccountBalanceInputBuilder::default()
    }
}

/// A builder for [`GetPbAccountBalanceInput`](crate::operation::get_pb_account_balance::GetPbAccountBalanceInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetPbAccountBalanceInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
}
impl GetPbAccountBalanceInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Consumes the builder and constructs a [`GetPbAccountBalanceInput`](crate::operation::get_pb_account_balance::GetPbAccountBalanceInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::get_pb_account_balance::GetPbAccountBalanceInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::get_pb_account_balance::GetPbAccountBalanceInput {
                account_id: self.account_id
                ,
            }
        )
    }
}

