// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_make_payment_input_input(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::operation::make_payment::MakePaymentInput,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.amount {
        object.key("amount").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::NegInt((*var_1).into()));
    }
    if let Some(var_2) = &input.description {
        object.key("description").string(var_2.as_str());
    }
    if let Some(var_3) = &input.merchant_id {
        object.key("merchant_id").string(var_3.as_str());
    }
    if let Some(var_4) = &input.merchant_mcc {
        object.key("merchant_mcc").string(var_4.as_str());
    }
    Ok(())
}

