// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_get_balance_http_error(
    _response_status: u16,
    _response_headers: &::aws_smithy_runtime_api::http::Headers,
    _response_body: &[u8],
) -> std::result::Result<crate::operation::get_balance::GetBalanceOutput, crate::operation::get_balance::GetBalanceError> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body)
        .map_err(crate::operation::get_balance::GetBalanceError::unhandled)?;
    let generic = generic_builder.build();
    let error_code = match generic.code() {
        Some(code) => code,
        None => return Err(crate::operation::get_balance::GetBalanceError::unhandled(generic)),
    };

    let _error_message = generic.message().map(|msg| msg.to_owned());
    Err(match error_code {
        "AccountNotFoundError" => crate::operation::get_balance::GetBalanceError::AccountNotFoundError({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::AccountNotFoundErrorBuilder::default();
                output = crate::protocol_serde::shape_account_not_found_error::de_account_not_found_error_json_err(_response_body, output)
                    .map_err(crate::operation::get_balance::GetBalanceError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::account_not_found_error_correct_errors(output)
                    .build()
                    .map_err(crate::operation::get_balance::GetBalanceError::unhandled)?
            };
            tmp
        }),
        _ => crate::operation::get_balance::GetBalanceError::generic(generic),
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_get_balance_http_response(
    _response_status: u16,
    _response_headers: &::aws_smithy_runtime_api::http::Headers,
    _response_body: &[u8],
) -> std::result::Result<crate::operation::get_balance::GetBalanceOutput, crate::operation::get_balance::GetBalanceError> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::get_balance::builders::GetBalanceOutputBuilder::default();
        output = crate::protocol_serde::shape_get_balance::de_get_balance(_response_body, output)
            .map_err(crate::operation::get_balance::GetBalanceError::unhandled)?;
        crate::serde_util::get_balance_output_output_correct_errors(output)
            .build()
            .map_err(crate::operation::get_balance::GetBalanceError::unhandled)?
    })
}

pub(crate) fn de_get_balance(
    value: &[u8],
    mut builder: crate::operation::get_balance::builders::GetBalanceOutputBuilder,
) -> ::std::result::Result<crate::operation::get_balance::builders::GetBalanceOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError>
{
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
    let tokens = &mut tokens_owned;
    ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => match key.to_unescaped()?.as_ref() {
                "accountId" => {
                    builder = builder.set_account_id(
                        ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                    );
                }
                "othersContribution" => {
                    builder = builder.set_others_contribution(
                        ::aws_smithy_json::deserialize::token::expect_number_or_null(tokens.next())?
                            .map(i64::try_from)
                            .transpose()?,
                    );
                }
                "selfContribution" => {
                    builder = builder.set_self_contribution(
                        ::aws_smithy_json::deserialize::token::expect_number_or_null(tokens.next())?
                            .map(i64::try_from)
                            .transpose()?,
                    );
                }
                "total" => {
                    builder = builder.set_total(
                        ::aws_smithy_json::deserialize::token::expect_number_or_null(tokens.next())?
                            .map(i64::try_from)
                            .transpose()?,
                    );
                }
                _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
            },
            other => {
                return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!(
                    "expected object key or end object, found: {:?}",
                    other
                )))
            }
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "found more JSON tokens after completing parsing",
        ));
    }
    Ok(builder)
}
