// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_return_pb_account_contribution_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::return_pb_account_contribution::ReturnPbAccountContributionOutput, crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?;
    let generic = generic_builder.build();
    let error_code = match generic.code() {
                                Some(code) => code,
                                None => return Err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled(generic))
                            };
    
                            let _error_message = generic.message().map(|msg|msg.to_owned());
    Err(match error_code {
        "AccountNotFoundError" => crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::AccountNotFoundError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::AccountNotFoundErrorBuilder::default();
                    output = crate::protocol_serde::shape_account_not_found_error::de_account_not_found_error_json_err(_response_body, output).map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::account_not_found_error_correct_errors(output).build().map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?
                }
            ;
            tmp
        }),
        "AccountNotActiveError" => crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::AccountNotActiveError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::AccountNotActiveErrorBuilder::default();
                    output = crate::protocol_serde::shape_account_not_active_error::de_account_not_active_error_json_err(_response_body, output).map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::account_not_active_error_correct_errors(output).build().map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?
                }
            ;
            tmp
        }),
        "ContributionAmountInvalidError" => crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::ContributionAmountInvalidError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::ContributionAmountInvalidErrorBuilder::default();
                    output = crate::protocol_serde::shape_contribution_amount_invalid_error::de_contribution_amount_invalid_error_json_err(_response_body, output).map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::contribution_amount_invalid_error_correct_errors(output).build().map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?
                }
            ;
            tmp
        }),
        "ContributionFullyReturnedError" => crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::ContributionFullyReturnedError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::ContributionFullyReturnedErrorBuilder::default();
                    output = crate::protocol_serde::shape_contribution_fully_returned_error::de_contribution_fully_returned_error_json_err(_response_body, output).map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::contribution_fully_returned_error_correct_errors(output).build().map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?
                }
            ;
            tmp
        }),
        _ => crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::generic(generic)
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_return_pb_account_contribution_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::return_pb_account_contribution::ReturnPbAccountContributionOutput, crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::return_pb_account_contribution::builders::ReturnPbAccountContributionOutputBuilder::default();
        output = crate::protocol_serde::shape_return_pb_account_contribution::de_return_pb_account_contribution(_response_body, output).map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?;
        crate::serde_util::return_pb_account_contribution_output_output_correct_errors(output).build().map_err(crate::operation::return_pb_account_contribution::ReturnPBAccountContributionError::unhandled)?
    })
}

pub fn ser_return_pb_account_contribution_input(input: &crate::operation::return_pb_account_contribution::ReturnPbAccountContributionInput) -> ::std::result::Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_return_pb_account_contribution_input::ser_return_pb_account_contribution_input_input(&mut object, input)?;
    object.finish();
    Ok(::aws_smithy_types::body::SdkBody::from(out))
}

pub(crate) fn de_return_pb_account_contribution(value: &[u8], mut builder: crate::operation::return_pb_account_contribution::builders::ReturnPbAccountContributionOutputBuilder) -> ::std::result::Result<crate::operation::return_pb_account_contribution::builders::ReturnPbAccountContributionOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
                        let tokens = &mut tokens_owned;
                        ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                match key.to_unescaped()?.as_ref() {
                    "account_id" => {
                        builder = builder.set_account_id(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "allocations" => {
                        builder = builder.set_allocations(
                            crate::protocol_serde::shape_allocation_entries::de_allocation_entries(tokens)?
                        );
                    }
                    "amount" => {
                        builder = builder.set_amount(
                            ::aws_smithy_json::deserialize::token::expect_number_or_null(tokens.next())?
                                                .map(i64::try_from)
                                                .transpose()?
                        );
                    }
                    "correlation_id" => {
                        builder = builder.set_correlation_id(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "created_at" => {
                        builder = builder.set_created_at(
                            ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
                        );
                    }
                    "funding_type" => {
                        builder = builder.set_funding_type(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    crate::types::FundingType::from(u.as_ref())
                                )
                            ).transpose()?
                        );
                    }
                    "remaining_returnable_after" => {
                        builder = builder.set_remaining_returnable_after(
                            ::aws_smithy_json::deserialize::token::expect_number_or_null(tokens.next())?
                                                .map(i64::try_from)
                                                .transpose()?
                        );
                    }
                    "return_id" => {
                        builder = builder.set_return_id(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "status" => {
                        builder = builder.set_status(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    crate::types::TransactionStatus::from(u.as_ref())
                                )
                            ).transpose()?
                        );
                    }
                    _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
                }
            }
            other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
    }
    Ok(builder)
}

