// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_deposit_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::deposit::DepositInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.amount {
        object.key("amount").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_1).into()),
        );
    }
    if let Some(var_2) = &input.source_account_number {
        object.key("sourceAccountNumber").string(var_2.as_str());
    }
    if let Some(var_3) = &input.source_ifsc {
        object.key("sourceIfsc").string(var_3.as_str());
    }
    Ok(())
}
