// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_withdraw_from_normal_account_input_input(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::operation::withdraw_from_normal_account::WithdrawFromNormalAccountInput,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.amount {
        object.key("amount").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::NegInt((*var_1).into()));
    }
    if let Some(var_2) = &input.description {
        object.key("description").string(var_2.as_str());
    }
    if let Some(var_3) = &input.gateway_ref {
        object.key("gateway_ref").string(var_3.as_str());
    }
    if let Some(var_4) = &input.idempotency_key {
        object.key("idempotency_key").string(var_4.as_str());
    }
    Ok(())
}

