// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_account_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::create_account::CreateAccountInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.holder_id {
        object.key("holderId").string(var_1.as_str());
    }
    if let Some(var_2) = &input.origin_account_number {
        object.key("originAccountNumber").string(var_2.as_str());
    }
    if let Some(var_3) = &input.origin_ifsc {
        object.key("originIfsc").string(var_3.as_str());
    }
    if let Some(var_4) = &input.purpose_code {
        object.key("purposeCode").string(var_4.as_str());
    }
    Ok(())
}
