// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_deposit_to_pb_account_input_input(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::operation::deposit_to_pb_account::DepositToPbAccountInput,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.amount {
        object.key("amount").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::NegInt((*var_1).into()));
    }
    if let Some(var_2) = &input.funding_type {
        object.key("funding_type").string(var_2.as_str());
    }
    if let Some(var_3) = &input.gateway_ref {
        object.key("gateway_ref").string(var_3.as_str());
    }
    if let Some(var_4) = &input.idempotency_key {
        object.key("idempotency_key").string(var_4.as_str());
    }
    if let Some(var_5) = &input.pending {
        object.key("pending").boolean(*var_5);
    }
    if let Some(var_6) = &input.source_account_number {
        object.key("source_account_number").string(var_6.as_str());
    }
    if let Some(var_7) = &input.source_ifsc {
        object.key("source_ifsc").string(var_7.as_str());
    }
    if let Some(var_8) = &input.timeout_seconds {
        object.key("timeout_seconds").number(#[allow(clippy::useless_conversion)]::aws_smithy_types::Number::NegInt((*var_8).into()));
    }
    Ok(())
}

