// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_create_pb_account_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::create_pb_account::CreatePbAccountOutput, crate::operation::create_pb_account::CreatePBAccountError> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::create_pb_account::CreatePBAccountError::unhandled)?;
    let generic = generic_builder.build();
    let error_code = match generic.code() {
                                Some(code) => code,
                                None => return Err(crate::operation::create_pb_account::CreatePBAccountError::unhandled(generic))
                            };
    
                            let _error_message = generic.message().map(|msg|msg.to_owned());
    Err(match error_code {
        "PurposeTypeNotFoundError" => crate::operation::create_pb_account::CreatePBAccountError::PurposeTypeNotFoundError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::PurposeTypeNotFoundErrorBuilder::default();
                    output = crate::protocol_serde::shape_purpose_type_not_found_error::de_purpose_type_not_found_error_json_err(_response_body, output).map_err(crate::operation::create_pb_account::CreatePBAccountError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::purpose_type_not_found_error_correct_errors(output).build().map_err(crate::operation::create_pb_account::CreatePBAccountError::unhandled)?
                }
            ;
            tmp
        }),
        _ => crate::operation::create_pb_account::CreatePBAccountError::generic(generic)
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_create_pb_account_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::create_pb_account::CreatePbAccountOutput, crate::operation::create_pb_account::CreatePBAccountError> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::create_pb_account::builders::CreatePbAccountOutputBuilder::default();
        output = crate::protocol_serde::shape_create_pb_account::de_create_pb_account(_response_body, output).map_err(crate::operation::create_pb_account::CreatePBAccountError::unhandled)?;
        crate::serde_util::create_pb_account_output_output_correct_errors(output).build().map_err(crate::operation::create_pb_account::CreatePBAccountError::unhandled)?
    })
}

pub fn ser_create_pb_account_input(input: &crate::operation::create_pb_account::CreatePbAccountInput) -> ::std::result::Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_create_pb_account_input::ser_create_pb_account_input_input(&mut object, input)?;
    object.finish();
    Ok(::aws_smithy_types::body::SdkBody::from(out))
}

pub(crate) fn de_create_pb_account(value: &[u8], mut builder: crate::operation::create_pb_account::builders::CreatePbAccountOutputBuilder) -> ::std::result::Result<crate::operation::create_pb_account::builders::CreatePbAccountOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
                        let tokens = &mut tokens_owned;
                        ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                match key.to_unescaped()?.as_ref() {
                    "created_at" => {
                        builder = builder.set_created_at(
                            ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
                        );
                    }
                    "holder_id" => {
                        builder = builder.set_holder_id(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "id" => {
                        builder = builder.set_id(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "kyc_tier" => {
                        builder = builder.set_kyc_tier(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "origin_account_number" => {
                        builder = builder.set_origin_account_number(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "origin_ifsc" => {
                        builder = builder.set_origin_ifsc(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "purpose_code" => {
                        builder = builder.set_purpose_code(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "status" => {
                        builder = builder.set_status(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "updated_at" => {
                        builder = builder.set_updated_at(
                            ::aws_smithy_json::deserialize::token::expect_timestamp_or_null(tokens.next(), ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
                        );
                    }
                    "virtual_account_number" => {
                        builder = builder.set_virtual_account_number(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "virtual_ifsc" => {
                        builder = builder.set_virtual_ifsc(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "vpa" => {
                        builder = builder.set_vpa(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
                }
            }
            other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
    }
    Ok(builder)
}

