// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct VoidPbAccountContributionReturnInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub return_id: ::std::option::Option<::std::string::String>,
}
impl  VoidPbAccountContributionReturnInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn return_id(&self) -> ::std::option::Option<&str> {
        self.return_id.as_deref()
    }
}
impl VoidPbAccountContributionReturnInput {
    /// Creates a new builder-style object to manufacture [`VoidPbAccountContributionReturnInput`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnInput).
    pub fn builder() -> crate::operation::void_pb_account_contribution_return::builders::VoidPbAccountContributionReturnInputBuilder {
        crate::operation::void_pb_account_contribution_return::builders::VoidPbAccountContributionReturnInputBuilder::default()
    }
}

/// A builder for [`VoidPbAccountContributionReturnInput`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct VoidPbAccountContributionReturnInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) return_id: ::std::option::Option<::std::string::String>,
}
impl VoidPbAccountContributionReturnInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn return_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.return_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_return_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.return_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_return_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.return_id
    }
    /// Consumes the builder and constructs a [`VoidPbAccountContributionReturnInput`](crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::void_pb_account_contribution_return::VoidPbAccountContributionReturnInput {
                account_id: self.account_id
                ,
                return_id: self.return_id
                ,
            }
        )
    }
}

