// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetBalanceInput {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
}
impl GetBalanceInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
}
impl GetBalanceInput {
    /// Creates a new builder-style object to manufacture [`GetBalanceInput`](crate::operation::get_balance::GetBalanceInput).
    pub fn builder() -> crate::operation::get_balance::builders::GetBalanceInputBuilder {
        crate::operation::get_balance::builders::GetBalanceInputBuilder::default()
    }
}

/// A builder for [`GetBalanceInput`](crate::operation::get_balance::GetBalanceInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetBalanceInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
}
impl GetBalanceInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Consumes the builder and constructs a [`GetBalanceInput`](crate::operation::get_balance::GetBalanceInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::get_balance::GetBalanceInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::get_balance::GetBalanceInput { account_id: self.account_id })
    }
}
