// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct TransferToPbAccountOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub transfer_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub source_account_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub destination_account_id: ::std::string::String,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: i64,
    #[allow(missing_docs)] // documentation missing in model
    pub status: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub correlation_id: ::std::string::String,
    /// ISO 8601 date-time.
    pub created_at: ::aws_smithy_types::DateTime,
}
impl  TransferToPbAccountOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn transfer_id(&self) -> &str {
        use std::ops::Deref; self.transfer_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn source_account_id(&self) -> &str {
        use std::ops::Deref; self.source_account_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn destination_account_id(&self) -> &str {
        use std::ops::Deref; self.destination_account_id.deref()
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> i64 {
        self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> &str {
        use std::ops::Deref; self.status.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn correlation_id(&self) -> &str {
        use std::ops::Deref; self.correlation_id.deref()
    }
    /// ISO 8601 date-time.
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
}
impl TransferToPbAccountOutput {
    /// Creates a new builder-style object to manufacture [`TransferToPbAccountOutput`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput).
    pub fn builder() -> crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder {
        crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder::default()
    }
}

/// A builder for [`TransferToPbAccountOutput`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct TransferToPbAccountOutputBuilder {
    pub(crate) transfer_id: ::std::option::Option<::std::string::String>,
    pub(crate) source_account_id: ::std::option::Option<::std::string::String>,
    pub(crate) destination_account_id: ::std::option::Option<::std::string::String>,
    pub(crate) amount: ::std::option::Option<i64>,
    pub(crate) status: ::std::option::Option<::std::string::String>,
    pub(crate) correlation_id: ::std::option::Option<::std::string::String>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl TransferToPbAccountOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn transfer_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.transfer_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_transfer_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.transfer_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_transfer_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.transfer_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn source_account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.source_account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_source_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.source_account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_source_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.source_account_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn destination_account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.destination_account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_destination_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.destination_account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_destination_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.destination_account_id
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn status(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.status = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<::std::string::String> {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn correlation_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.correlation_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_correlation_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.correlation_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_correlation_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.correlation_id
    }
    /// ISO 8601 date-time.
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    /// ISO 8601 date-time.
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input; self
    }
    /// ISO 8601 date-time.
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    /// Consumes the builder and constructs a [`TransferToPbAccountOutput`](crate::operation::transfer_to_pb_account::TransferToPbAccountOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`transfer_id`](crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder::transfer_id)
    /// - [`source_account_id`](crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder::source_account_id)
    /// - [`destination_account_id`](crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder::destination_account_id)
    /// - [`amount`](crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder::amount)
    /// - [`status`](crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder::status)
    /// - [`correlation_id`](crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder::correlation_id)
    /// - [`created_at`](crate::operation::transfer_to_pb_account::builders::TransferToPbAccountOutputBuilder::created_at)
    pub fn build(self) -> ::std::result::Result<crate::operation::transfer_to_pb_account::TransferToPbAccountOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::transfer_to_pb_account::TransferToPbAccountOutput {
                transfer_id: self.transfer_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("transfer_id", "transfer_id was not specified but it is required when building TransferToPbAccountOutput")
                    )?
                ,
                source_account_id: self.source_account_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("source_account_id", "source_account_id was not specified but it is required when building TransferToPbAccountOutput")
                    )?
                ,
                destination_account_id: self.destination_account_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("destination_account_id", "destination_account_id was not specified but it is required when building TransferToPbAccountOutput")
                    )?
                ,
                amount: self.amount
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("amount", "amount was not specified but it is required when building TransferToPbAccountOutput")
                    )?
                ,
                status: self.status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("status", "status was not specified but it is required when building TransferToPbAccountOutput")
                    )?
                ,
                correlation_id: self.correlation_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("correlation_id", "correlation_id was not specified but it is required when building TransferToPbAccountOutput")
                    )?
                ,
                created_at: self.created_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("created_at", "created_at was not specified but it is required when building TransferToPbAccountOutput")
                    )?
                ,
            }
        )
    }
}

