// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct AccountNotActiveError {
    #[allow(missing_docs)] // documentation missing in model
    pub error: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::string::String,
    pub(crate) meta: ::aws_smithy_types::error::ErrorMetadata,
}
impl AccountNotActiveError {
    #[allow(missing_docs)] // documentation missing in model
    pub fn error(&self) -> &str {
        use std::ops::Deref;
        self.error.deref()
    }
}
impl AccountNotActiveError {
    /// Returns the error message.
    pub fn message(&self) -> &str {
        &self.message
    }
}
impl ::std::fmt::Display for AccountNotActiveError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "AccountNotActiveError")?;
        {
            ::std::write!(f, ": {}", &self.message)?;
        }
        Ok(())
    }
}
impl ::std::error::Error for AccountNotActiveError {}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for AccountNotActiveError {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata {
        &self.meta
    }
}
impl AccountNotActiveError {
    /// Creates a new builder-style object to manufacture [`AccountNotActiveError`](crate::types::error::AccountNotActiveError).
    pub fn builder() -> crate::types::error::builders::AccountNotActiveErrorBuilder {
        crate::types::error::builders::AccountNotActiveErrorBuilder::default()
    }
}

/// A builder for [`AccountNotActiveError`](crate::types::error::AccountNotActiveError).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct AccountNotActiveErrorBuilder {
    pub(crate) error: ::std::option::Option<::std::string::String>,
    pub(crate) message: ::std::option::Option<::std::string::String>,
    meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
}
impl AccountNotActiveErrorBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn error(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.error = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_error(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.error = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_error(&self) -> &::std::option::Option<::std::string::String> {
        &self.error
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Sets error metadata
    pub fn meta(mut self, meta: ::aws_smithy_types::error::ErrorMetadata) -> Self {
        self.meta = Some(meta);
        self
    }

    /// Sets error metadata
    pub fn set_meta(&mut self, meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>) -> &mut Self {
        self.meta = meta;
        self
    }
    /// Consumes the builder and constructs a [`AccountNotActiveError`](crate::types::error::AccountNotActiveError).
    /// This method will fail if any of the following fields are not set:
    /// - [`error`](crate::types::error::builders::AccountNotActiveErrorBuilder::error)
    /// - [`message`](crate::types::error::builders::AccountNotActiveErrorBuilder::message)
    pub fn build(self) -> ::std::result::Result<crate::types::error::AccountNotActiveError, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::error::AccountNotActiveError {
            error: self.error.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "error",
                    "error was not specified but it is required when building AccountNotActiveError",
                )
            })?,
            message: self.message.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "message",
                    "message was not specified but it is required when building AccountNotActiveError",
                )
            })?,
            meta: self.meta.unwrap_or_default(),
        })
    }
}
