// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ContributionAmountInvalidError  {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::string::String,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub requested: i64,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub remaining: i64,
    pub(crate) meta: ::aws_smithy_types::error::ErrorMetadata,
}
impl  ContributionAmountInvalidError  {
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn requested(&self) -> i64 {
        self.requested
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn remaining(&self) -> i64 {
        self.remaining
    }
}
impl ContributionAmountInvalidError {
    /// Returns the error message.
                        pub fn message(&self) -> &str { &self.message }
}
impl ::std::fmt::Display for ContributionAmountInvalidError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ContributionAmountInvalidError")?;
         {
            ::std::write!(f, ": {}", &self.message)?;
        }
        Ok(())
    }
}
impl ::std::error::Error for ContributionAmountInvalidError {}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for ContributionAmountInvalidError {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata { &self.meta }
}
impl ContributionAmountInvalidError {
    /// Creates a new builder-style object to manufacture [`ContributionAmountInvalidError`](crate::types::error::ContributionAmountInvalidError).
    pub fn builder() -> crate::types::error::builders::ContributionAmountInvalidErrorBuilder {
        crate::types::error::builders::ContributionAmountInvalidErrorBuilder::default()
    }
}

/// A builder for [`ContributionAmountInvalidError`](crate::types::error::ContributionAmountInvalidError).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ContributionAmountInvalidErrorBuilder {
    pub(crate) message: ::std::option::Option<::std::string::String>,
    pub(crate) requested: ::std::option::Option<i64>,
    pub(crate) remaining: ::std::option::Option<i64>,
    meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
}
impl ContributionAmountInvalidErrorBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn requested(mut self, input: i64) -> Self {
        self.requested = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_requested(mut self, input: ::std::option::Option<i64>) -> Self {
        self.requested = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_requested(&self) -> &::std::option::Option<i64> {
        &self.requested
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn remaining(mut self, input: i64) -> Self {
        self.remaining = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_remaining(mut self, input: ::std::option::Option<i64>) -> Self {
        self.remaining = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_remaining(&self) -> &::std::option::Option<i64> {
        &self.remaining
    }
    /// Sets error metadata
                                                pub fn meta(mut self, meta: ::aws_smithy_types::error::ErrorMetadata) -> Self {
                                                    self.meta = Some(meta);
                                                    self
                                                }
    
                                                /// Sets error metadata
                                                pub fn set_meta(&mut self, meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>) -> &mut Self {
                                                    self.meta = meta;
                                                    self
                                                }
    /// Consumes the builder and constructs a [`ContributionAmountInvalidError`](crate::types::error::ContributionAmountInvalidError).
    /// This method will fail if any of the following fields are not set:
    /// - [`message`](crate::types::error::builders::ContributionAmountInvalidErrorBuilder::message)
    /// - [`requested`](crate::types::error::builders::ContributionAmountInvalidErrorBuilder::requested)
    /// - [`remaining`](crate::types::error::builders::ContributionAmountInvalidErrorBuilder::remaining)
    pub fn build(self) -> ::std::result::Result<crate::types::error::ContributionAmountInvalidError, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::error::ContributionAmountInvalidError {
                message: self.message
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("message", "message was not specified but it is required when building ContributionAmountInvalidError")
                    )?
                ,
                requested: self.requested
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("requested", "requested was not specified but it is required when building ContributionAmountInvalidError")
                    )?
                ,
                remaining: self.remaining
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("remaining", "remaining was not specified but it is required when building ContributionAmountInvalidError")
                    )?
                ,
                meta: self.meta.unwrap_or_default(),
            }
        )
    }
}

