// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UpdateAccountStatusInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
    /// Account status.
    pub status: ::std::option::Option<crate::types::Status>,
}
impl  UpdateAccountStatusInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
    /// Account status.
    pub fn status(&self) -> ::std::option::Option<&crate::types::Status> {
        self.status.as_ref()
    }
}
impl UpdateAccountStatusInput {
    /// Creates a new builder-style object to manufacture [`UpdateAccountStatusInput`](crate::operation::update_account_status::UpdateAccountStatusInput).
    pub fn builder() -> crate::operation::update_account_status::builders::UpdateAccountStatusInputBuilder {
        crate::operation::update_account_status::builders::UpdateAccountStatusInputBuilder::default()
    }
}

/// A builder for [`UpdateAccountStatusInput`](crate::operation::update_account_status::UpdateAccountStatusInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UpdateAccountStatusInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) status: ::std::option::Option<crate::types::Status>,
}
impl UpdateAccountStatusInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Account status.
    /// This field is required.
    pub fn status(mut self, input: crate::types::Status) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    /// Account status.
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::Status>) -> Self {
        self.status = input; self
    }
    /// Account status.
    pub fn get_status(&self) -> &::std::option::Option<crate::types::Status> {
        &self.status
    }
    /// Consumes the builder and constructs a [`UpdateAccountStatusInput`](crate::operation::update_account_status::UpdateAccountStatusInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::update_account_status::UpdateAccountStatusInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::update_account_status::UpdateAccountStatusInput {
                account_id: self.account_id
                ,
                status: self.status
                ,
            }
        )
    }
}

