// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct MakePbAccountPaymentOutput  {
    /// Stable identifier for this payment. For split payments, this is also the correlation_id linking the per-pool legs.
    pub payment_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::string::String,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: i64,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub from_others: i64,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub from_self: i64,
    #[allow(missing_docs)] // documentation missing in model
    pub merchant_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub merchant_mcc: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub gateway_ref: ::std::option::Option<::std::string::String>,
}
impl  MakePbAccountPaymentOutput  {
    /// Stable identifier for this payment. For split payments, this is also the correlation_id linking the per-pool legs.
    pub fn payment_id(&self) -> &str {
        use std::ops::Deref; self.payment_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> &str {
        use std::ops::Deref; self.account_id.deref()
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> i64 {
        self.amount
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn from_others(&self) -> i64 {
        self.from_others
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn from_self(&self) -> i64 {
        self.from_self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn merchant_id(&self) -> &str {
        use std::ops::Deref; self.merchant_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn merchant_mcc(&self) -> &str {
        use std::ops::Deref; self.merchant_mcc.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(&self) -> ::std::option::Option<&str> {
        self.gateway_ref.as_deref()
    }
}
impl MakePbAccountPaymentOutput {
    /// Creates a new builder-style object to manufacture [`MakePbAccountPaymentOutput`](crate::operation::make_pb_account_payment::MakePbAccountPaymentOutput).
    pub fn builder() -> crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder {
        crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder::default()
    }
}

/// A builder for [`MakePbAccountPaymentOutput`](crate::operation::make_pb_account_payment::MakePbAccountPaymentOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct MakePbAccountPaymentOutputBuilder {
    pub(crate) payment_id: ::std::option::Option<::std::string::String>,
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) amount: ::std::option::Option<i64>,
    pub(crate) from_others: ::std::option::Option<i64>,
    pub(crate) from_self: ::std::option::Option<i64>,
    pub(crate) merchant_id: ::std::option::Option<::std::string::String>,
    pub(crate) merchant_mcc: ::std::option::Option<::std::string::String>,
    pub(crate) gateway_ref: ::std::option::Option<::std::string::String>,
}
impl MakePbAccountPaymentOutputBuilder {
    /// Stable identifier for this payment. For split payments, this is also the correlation_id linking the per-pool legs.
    /// This field is required.
    pub fn payment_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.payment_id = ::std::option::Option::Some(input.into());
        self
    }
    /// Stable identifier for this payment. For split payments, this is also the correlation_id linking the per-pool legs.
    pub fn set_payment_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.payment_id = input; self
    }
    /// Stable identifier for this payment. For split payments, this is also the correlation_id linking the per-pool legs.
    pub fn get_payment_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.payment_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn from_others(mut self, input: i64) -> Self {
        self.from_others = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_from_others(mut self, input: ::std::option::Option<i64>) -> Self {
        self.from_others = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_from_others(&self) -> &::std::option::Option<i64> {
        &self.from_others
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn from_self(mut self, input: i64) -> Self {
        self.from_self = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_from_self(mut self, input: ::std::option::Option<i64>) -> Self {
        self.from_self = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_from_self(&self) -> &::std::option::Option<i64> {
        &self.from_self
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn merchant_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.merchant_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_merchant_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.merchant_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_merchant_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.merchant_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn merchant_mcc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.merchant_mcc = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_merchant_mcc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.merchant_mcc = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_merchant_mcc(&self) -> &::std::option::Option<::std::string::String> {
        &self.merchant_mcc
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.gateway_ref = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_gateway_ref(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.gateway_ref = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_gateway_ref(&self) -> &::std::option::Option<::std::string::String> {
        &self.gateway_ref
    }
    /// Consumes the builder and constructs a [`MakePbAccountPaymentOutput`](crate::operation::make_pb_account_payment::MakePbAccountPaymentOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`payment_id`](crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder::payment_id)
    /// - [`account_id`](crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder::account_id)
    /// - [`amount`](crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder::amount)
    /// - [`from_others`](crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder::from_others)
    /// - [`from_self`](crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder::from_self)
    /// - [`merchant_id`](crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder::merchant_id)
    /// - [`merchant_mcc`](crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentOutputBuilder::merchant_mcc)
    pub fn build(self) -> ::std::result::Result<crate::operation::make_pb_account_payment::MakePbAccountPaymentOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::make_pb_account_payment::MakePbAccountPaymentOutput {
                payment_id: self.payment_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("payment_id", "payment_id was not specified but it is required when building MakePbAccountPaymentOutput")
                    )?
                ,
                account_id: self.account_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("account_id", "account_id was not specified but it is required when building MakePbAccountPaymentOutput")
                    )?
                ,
                amount: self.amount
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("amount", "amount was not specified but it is required when building MakePbAccountPaymentOutput")
                    )?
                ,
                from_others: self.from_others
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("from_others", "from_others was not specified but it is required when building MakePbAccountPaymentOutput")
                    )?
                ,
                from_self: self.from_self
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("from_self", "from_self was not specified but it is required when building MakePbAccountPaymentOutput")
                    )?
                ,
                merchant_id: self.merchant_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("merchant_id", "merchant_id was not specified but it is required when building MakePbAccountPaymentOutput")
                    )?
                ,
                merchant_mcc: self.merchant_mcc
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("merchant_mcc", "merchant_mcc was not specified but it is required when building MakePbAccountPaymentOutput")
                    )?
                ,
                gateway_ref: self.gateway_ref
                ,
            }
        )
    }
}

