// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct MakePbAccountPaymentInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: ::std::option::Option<i64>,
    #[allow(missing_docs)] // documentation missing in model
    pub merchant_mcc: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub merchant_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub description: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub idempotency_key: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub gateway_ref: ::std::option::Option<::std::string::String>,
}
impl  MakePbAccountPaymentInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> ::std::option::Option<i64> {
        self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn merchant_mcc(&self) -> ::std::option::Option<&str> {
        self.merchant_mcc.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn merchant_id(&self) -> ::std::option::Option<&str> {
        self.merchant_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn description(&self) -> ::std::option::Option<&str> {
        self.description.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(&self) -> ::std::option::Option<&str> {
        self.idempotency_key.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(&self) -> ::std::option::Option<&str> {
        self.gateway_ref.as_deref()
    }
}
impl MakePbAccountPaymentInput {
    /// Creates a new builder-style object to manufacture [`MakePbAccountPaymentInput`](crate::operation::make_pb_account_payment::MakePbAccountPaymentInput).
    pub fn builder() -> crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentInputBuilder {
        crate::operation::make_pb_account_payment::builders::MakePbAccountPaymentInputBuilder::default()
    }
}

/// A builder for [`MakePbAccountPaymentInput`](crate::operation::make_pb_account_payment::MakePbAccountPaymentInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct MakePbAccountPaymentInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) amount: ::std::option::Option<i64>,
    pub(crate) merchant_mcc: ::std::option::Option<::std::string::String>,
    pub(crate) merchant_id: ::std::option::Option<::std::string::String>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) idempotency_key: ::std::option::Option<::std::string::String>,
    pub(crate) gateway_ref: ::std::option::Option<::std::string::String>,
}
impl MakePbAccountPaymentInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn merchant_mcc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.merchant_mcc = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_merchant_mcc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.merchant_mcc = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_merchant_mcc(&self) -> &::std::option::Option<::std::string::String> {
        &self.merchant_mcc
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn merchant_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.merchant_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_merchant_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.merchant_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_merchant_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.merchant_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idempotency_key = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_idempotency_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idempotency_key = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_idempotency_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.idempotency_key
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.gateway_ref = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_gateway_ref(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.gateway_ref = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_gateway_ref(&self) -> &::std::option::Option<::std::string::String> {
        &self.gateway_ref
    }
    /// Consumes the builder and constructs a [`MakePbAccountPaymentInput`](crate::operation::make_pb_account_payment::MakePbAccountPaymentInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::make_pb_account_payment::MakePbAccountPaymentInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::make_pb_account_payment::MakePbAccountPaymentInput {
                account_id: self.account_id
                ,
                amount: self.amount
                ,
                merchant_mcc: self.merchant_mcc
                ,
                merchant_id: self.merchant_id
                ,
                description: self.description
                ,
                idempotency_key: self.idempotency_key
                ,
                gateway_ref: self.gateway_ref
                ,
            }
        )
    }
}

