// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct VoidPbAccountRefundInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub refund_id: ::std::option::Option<::std::string::String>,
}
impl  VoidPbAccountRefundInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn refund_id(&self) -> ::std::option::Option<&str> {
        self.refund_id.as_deref()
    }
}
impl VoidPbAccountRefundInput {
    /// Creates a new builder-style object to manufacture [`VoidPbAccountRefundInput`](crate::operation::void_pb_account_refund::VoidPbAccountRefundInput).
    pub fn builder() -> crate::operation::void_pb_account_refund::builders::VoidPbAccountRefundInputBuilder {
        crate::operation::void_pb_account_refund::builders::VoidPbAccountRefundInputBuilder::default()
    }
}

/// A builder for [`VoidPbAccountRefundInput`](crate::operation::void_pb_account_refund::VoidPbAccountRefundInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct VoidPbAccountRefundInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) refund_id: ::std::option::Option<::std::string::String>,
}
impl VoidPbAccountRefundInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn refund_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.refund_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_refund_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.refund_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_refund_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.refund_id
    }
    /// Consumes the builder and constructs a [`VoidPbAccountRefundInput`](crate::operation::void_pb_account_refund::VoidPbAccountRefundInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::void_pb_account_refund::VoidPbAccountRefundInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::void_pb_account_refund::VoidPbAccountRefundInput {
                account_id: self.account_id
                ,
                refund_id: self.refund_id
                ,
            }
        )
    }
}

