// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn purpose_type_not_found_error_correct_errors(mut builder: crate::types::error::builders::PurposeTypeNotFoundErrorBuilder) -> crate::types::error::builders::PurposeTypeNotFoundErrorBuilder {
                if builder.error.is_none() { builder.error = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn duplicate_account_error_correct_errors(mut builder: crate::types::error::builders::DuplicateAccountErrorBuilder) -> crate::types::error::builders::DuplicateAccountErrorBuilder {
                if builder.error.is_none() { builder.error = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn create_account_output_output_correct_errors(mut builder: crate::operation::create_account::builders::CreateAccountOutputBuilder) -> crate::operation::create_account::builders::CreateAccountOutputBuilder {
                if builder.id.is_none() { builder.id = Some(Default::default()) }
if builder.holder_id.is_none() { builder.holder_id = Some(Default::default()) }
if builder.purpose_code.is_none() { builder.purpose_code = Some(Default::default()) }
if builder.origin_ifsc.is_none() { builder.origin_ifsc = Some(Default::default()) }
if builder.origin_account_number.is_none() { builder.origin_account_number = Some(Default::default()) }
if builder.kyc_tier.is_none() { builder.kyc_tier = Some(Default::default()) }
if builder.status.is_none() { builder.status = Some(Default::default()) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
if builder.updated_at.is_none() { builder.updated_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn account_not_found_error_correct_errors(mut builder: crate::types::error::builders::AccountNotFoundErrorBuilder) -> crate::types::error::builders::AccountNotFoundErrorBuilder {
                if builder.error.is_none() { builder.error = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn account_not_active_error_correct_errors(mut builder: crate::types::error::builders::AccountNotActiveErrorBuilder) -> crate::types::error::builders::AccountNotActiveErrorBuilder {
                if builder.error.is_none() { builder.error = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn deposit_output_output_correct_errors(mut builder: crate::operation::deposit::builders::DepositOutputBuilder) -> crate::operation::deposit::builders::DepositOutputBuilder {
                if builder.deposit_id.is_none() { builder.deposit_id = Some(Default::default()) }
if builder.account_id.is_none() { builder.account_id = Some(Default::default()) }
if builder.amount.is_none() { builder.amount = Some(Default::default()) }
if builder.pool.is_none() { builder.pool = Some(Default::default()) }
if builder.status.is_none() { builder.status = Some(Default::default()) }
                builder
            }

pub(crate) fn get_account_output_output_correct_errors(mut builder: crate::operation::get_account::builders::GetAccountOutputBuilder) -> crate::operation::get_account::builders::GetAccountOutputBuilder {
                if builder.id.is_none() { builder.id = Some(Default::default()) }
if builder.holder_id.is_none() { builder.holder_id = Some(Default::default()) }
if builder.purpose_code.is_none() { builder.purpose_code = Some(Default::default()) }
if builder.origin_ifsc.is_none() { builder.origin_ifsc = Some(Default::default()) }
if builder.origin_account_number.is_none() { builder.origin_account_number = Some(Default::default()) }
if builder.kyc_tier.is_none() { builder.kyc_tier = Some(Default::default()) }
if builder.status.is_none() { builder.status = Some(Default::default()) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
if builder.updated_at.is_none() { builder.updated_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn get_balance_output_output_correct_errors(mut builder: crate::operation::get_balance::builders::GetBalanceOutputBuilder) -> crate::operation::get_balance::builders::GetBalanceOutputBuilder {
                if builder.account_id.is_none() { builder.account_id = Some(Default::default()) }
if builder.self_contribution.is_none() { builder.self_contribution = Some(Default::default()) }
if builder.others_contribution.is_none() { builder.others_contribution = Some(Default::default()) }
if builder.total.is_none() { builder.total = Some(Default::default()) }
if builder.pending_self.is_none() { builder.pending_self = Some(Default::default()) }
if builder.pending_others.is_none() { builder.pending_others = Some(Default::default()) }
                builder
            }

pub(crate) fn get_purpose_type_output_output_correct_errors(mut builder: crate::operation::get_purpose_type::builders::GetPurposeTypeOutputBuilder) -> crate::operation::get_purpose_type::builders::GetPurposeTypeOutputBuilder {
                if builder.purpose_code.is_none() { builder.purpose_code = Some(Default::default()) }
if builder.allowed_mccs.is_none() { builder.allowed_mccs = Some(Default::default()) }
                builder
            }

pub(crate) fn list_all_transactions_output_output_correct_errors(mut builder: crate::operation::list_all_transactions::builders::ListAllTransactionsOutputBuilder) -> crate::operation::list_all_transactions::builders::ListAllTransactionsOutputBuilder {
                if builder.transactions.is_none() { builder.transactions = Some(Default::default()) }
if builder.total.is_none() { builder.total = Some(Default::default()) }
if builder.offset.is_none() { builder.offset = Some(Default::default()) }
if builder.limit.is_none() { builder.limit = Some(Default::default()) }
                builder
            }

pub(crate) fn list_purpose_types_output_output_correct_errors(mut builder: crate::operation::list_purpose_types::builders::ListPurposeTypesOutputBuilder) -> crate::operation::list_purpose_types::builders::ListPurposeTypesOutputBuilder {
                if builder.purpose_types.is_none() { builder.purpose_types = Some(Default::default()) }
                builder
            }

pub(crate) fn list_transactions_output_output_correct_errors(mut builder: crate::operation::list_transactions::builders::ListTransactionsOutputBuilder) -> crate::operation::list_transactions::builders::ListTransactionsOutputBuilder {
                if builder.transactions.is_none() { builder.transactions = Some(Default::default()) }
if builder.total.is_none() { builder.total = Some(Default::default()) }
if builder.offset.is_none() { builder.offset = Some(Default::default()) }
if builder.limit.is_none() { builder.limit = Some(Default::default()) }
                builder
            }

pub(crate) fn invalid_mcc_error_correct_errors(mut builder: crate::types::error::builders::InvalidMccErrorBuilder) -> crate::types::error::builders::InvalidMccErrorBuilder {
                if builder.error.is_none() { builder.error = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn insufficient_funds_error_correct_errors(mut builder: crate::types::error::builders::InsufficientFundsErrorBuilder) -> crate::types::error::builders::InsufficientFundsErrorBuilder {
                if builder.error.is_none() { builder.error = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn make_payment_output_output_correct_errors(mut builder: crate::operation::make_payment::builders::MakePaymentOutputBuilder) -> crate::operation::make_payment::builders::MakePaymentOutputBuilder {
                if builder.account_id.is_none() { builder.account_id = Some(Default::default()) }
if builder.amount.is_none() { builder.amount = Some(Default::default()) }
if builder.from_others.is_none() { builder.from_others = Some(Default::default()) }
if builder.from_self.is_none() { builder.from_self = Some(Default::default()) }
if builder.merchant_id.is_none() { builder.merchant_id = Some(Default::default()) }
if builder.merchant_mcc.is_none() { builder.merchant_mcc = Some(Default::default()) }
                builder
            }

pub(crate) fn deposit_not_found_error_correct_errors(mut builder: crate::types::error::builders::DepositNotFoundErrorBuilder) -> crate::types::error::builders::DepositNotFoundErrorBuilder {
                if builder.error.is_none() { builder.error = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn deposit_not_pending_error_correct_errors(mut builder: crate::types::error::builders::DepositNotPendingErrorBuilder) -> crate::types::error::builders::DepositNotPendingErrorBuilder {
                if builder.error.is_none() { builder.error = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn post_deposit_output_output_correct_errors(mut builder: crate::operation::post_deposit::builders::PostDepositOutputBuilder) -> crate::operation::post_deposit::builders::PostDepositOutputBuilder {
                if builder.deposit_id.is_none() { builder.deposit_id = Some(Default::default()) }
if builder.account_id.is_none() { builder.account_id = Some(Default::default()) }
if builder.amount.is_none() { builder.amount = Some(Default::default()) }
if builder.pool.is_none() { builder.pool = Some(Default::default()) }
if builder.status.is_none() { builder.status = Some(Default::default()) }
                builder
            }

pub(crate) fn update_account_status_output_output_correct_errors(mut builder: crate::operation::update_account_status::builders::UpdateAccountStatusOutputBuilder) -> crate::operation::update_account_status::builders::UpdateAccountStatusOutputBuilder {
                if builder.id.is_none() { builder.id = Some(Default::default()) }
if builder.holder_id.is_none() { builder.holder_id = Some(Default::default()) }
if builder.purpose_code.is_none() { builder.purpose_code = Some(Default::default()) }
if builder.origin_ifsc.is_none() { builder.origin_ifsc = Some(Default::default()) }
if builder.origin_account_number.is_none() { builder.origin_account_number = Some(Default::default()) }
if builder.kyc_tier.is_none() { builder.kyc_tier = Some(Default::default()) }
if builder.status.is_none() { builder.status = Some(Default::default()) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
if builder.updated_at.is_none() { builder.updated_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn void_deposit_output_output_correct_errors(mut builder: crate::operation::void_deposit::builders::VoidDepositOutputBuilder) -> crate::operation::void_deposit::builders::VoidDepositOutputBuilder {
                if builder.deposit_id.is_none() { builder.deposit_id = Some(Default::default()) }
if builder.account_id.is_none() { builder.account_id = Some(Default::default()) }
if builder.amount.is_none() { builder.amount = Some(Default::default()) }
if builder.pool.is_none() { builder.pool = Some(Default::default()) }
if builder.status.is_none() { builder.status = Some(Default::default()) }
                builder
            }

pub(crate) fn withdraw_output_output_correct_errors(mut builder: crate::operation::withdraw::builders::WithdrawOutputBuilder) -> crate::operation::withdraw::builders::WithdrawOutputBuilder {
                if builder.account_id.is_none() { builder.account_id = Some(Default::default()) }
if builder.amount.is_none() { builder.amount = Some(Default::default()) }
                builder
            }

pub(crate) fn mcc_entry_correct_errors(mut builder: crate::types::builders::MccEntryBuilder) -> crate::types::builders::MccEntryBuilder {
                if builder.mcc.is_none() { builder.mcc = Some(Default::default()) }
                builder
            }

pub(crate) fn purpose_type_summary_correct_errors(mut builder: crate::types::builders::PurposeTypeSummaryBuilder) -> crate::types::builders::PurposeTypeSummaryBuilder {
                if builder.purpose_code.is_none() { builder.purpose_code = Some(Default::default()) }
if builder.allowed_mccs.is_none() { builder.allowed_mccs = Some(Default::default()) }
                builder
            }

pub(crate) fn transaction_summary_correct_errors(mut builder: crate::types::builders::TransactionSummaryBuilder) -> crate::types::builders::TransactionSummaryBuilder {
                if builder.id.is_none() { builder.id = Some(Default::default()) }
if builder.account_id.is_none() { builder.account_id = Some(Default::default()) }
if builder.r#type.is_none() { builder.r#type = "no value was set".parse::<crate::types::TransactionType>().ok() }
if builder.status.is_none() { builder.status = "no value was set".parse::<crate::types::TransactionStatus>().ok() }
if builder.amount.is_none() { builder.amount = Some(Default::default()) }
if builder.pool.is_none() { builder.pool = "no value was set".parse::<crate::types::PoolType>().ok() }
if builder.direction.is_none() { builder.direction = "no value was set".parse::<crate::types::TransactionDirection>().ok() }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

