// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct WithdrawInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::option::Option<::std::string::String>,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: ::std::option::Option<i64>,
}
impl  WithdrawInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> ::std::option::Option<&str> {
        self.account_id.as_deref()
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> ::std::option::Option<i64> {
        self.amount
    }
}
impl WithdrawInput {
    /// Creates a new builder-style object to manufacture [`WithdrawInput`](crate::operation::withdraw::WithdrawInput).
    pub fn builder() -> crate::operation::withdraw::builders::WithdrawInputBuilder {
        crate::operation::withdraw::builders::WithdrawInputBuilder::default()
    }
}

/// A builder for [`WithdrawInput`](crate::operation::withdraw::WithdrawInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct WithdrawInputBuilder {
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) amount: ::std::option::Option<i64>,
}
impl WithdrawInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    /// Consumes the builder and constructs a [`WithdrawInput`](crate::operation::withdraw::WithdrawInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::withdraw::WithdrawInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::withdraw::WithdrawInput {
                account_id: self.account_id
                ,
                amount: self.amount
                ,
            }
        )
    }
}

