// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct MccEntry  {
    #[allow(missing_docs)] // documentation missing in model
    pub mcc: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub description: ::std::option::Option<::std::string::String>,
}
impl  MccEntry  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn mcc(&self) -> &str {
        use std::ops::Deref; self.mcc.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn description(&self) -> ::std::option::Option<&str> {
        self.description.as_deref()
    }
}
impl MccEntry {
    /// Creates a new builder-style object to manufacture [`MccEntry`](crate::types::MccEntry).
    pub fn builder() -> crate::types::builders::MccEntryBuilder {
        crate::types::builders::MccEntryBuilder::default()
    }
}

/// A builder for [`MccEntry`](crate::types::MccEntry).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct MccEntryBuilder {
    pub(crate) mcc: ::std::option::Option<::std::string::String>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
}
impl MccEntryBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn mcc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.mcc = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_mcc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.mcc = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_mcc(&self) -> &::std::option::Option<::std::string::String> {
        &self.mcc
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    /// Consumes the builder and constructs a [`MccEntry`](crate::types::MccEntry).
    /// This method will fail if any of the following fields are not set:
    /// - [`mcc`](crate::types::builders::MccEntryBuilder::mcc)
    pub fn build(self) -> ::std::result::Result<crate::types::MccEntry, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::MccEntry {
                mcc: self.mcc
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("mcc", "mcc was not specified but it is required when building MccEntry")
                    )?
                ,
                description: self.description
                ,
            }
        )
    }
}

