// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct TransactionSummary  {
    #[allow(missing_docs)] // documentation missing in model
    pub id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub account_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub account_kind: ::std::string::String,
    /// Transaction type.
    pub r#type: crate::types::TransactionType,
    /// Transaction status.
    pub status: crate::types::TransactionStatus,
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub amount: i64,
    /// Pool type indicating the source of funds.
    pub pool: ::std::option::Option<crate::types::PoolType>,
    /// Transaction direction.
    pub direction: crate::types::TransactionDirection,
    #[allow(missing_docs)] // documentation missing in model
    pub description: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub void_reason: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub merchant_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub merchant_mcc: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub source_ifsc: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub source_account: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub gateway_ref: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub funding_type: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub correlation_id: ::std::option::Option<::std::string::String>,
    /// ISO 8601 date-time.
    pub created_at: ::aws_smithy_types::DateTime,
}
impl  TransactionSummary  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn id(&self) -> &str {
        use std::ops::Deref; self.id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_id(&self) -> &str {
        use std::ops::Deref; self.account_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn account_kind(&self) -> &str {
        use std::ops::Deref; self.account_kind.deref()
    }
    /// Transaction type.
    pub fn r#type(&self) -> &crate::types::TransactionType {
        &self.r#type
    }
    /// Transaction status.
    pub fn status(&self) -> &crate::types::TransactionStatus {
        &self.status
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn amount(&self) -> i64 {
        self.amount
    }
    /// Pool type indicating the source of funds.
    pub fn pool(&self) -> ::std::option::Option<&crate::types::PoolType> {
        self.pool.as_ref()
    }
    /// Transaction direction.
    pub fn direction(&self) -> &crate::types::TransactionDirection {
        &self.direction
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn description(&self) -> ::std::option::Option<&str> {
        self.description.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn void_reason(&self) -> ::std::option::Option<&str> {
        self.void_reason.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn merchant_id(&self) -> ::std::option::Option<&str> {
        self.merchant_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn merchant_mcc(&self) -> ::std::option::Option<&str> {
        self.merchant_mcc.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn source_ifsc(&self) -> ::std::option::Option<&str> {
        self.source_ifsc.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn source_account(&self) -> ::std::option::Option<&str> {
        self.source_account.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(&self) -> ::std::option::Option<&str> {
        self.gateway_ref.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn funding_type(&self) -> ::std::option::Option<&str> {
        self.funding_type.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn correlation_id(&self) -> ::std::option::Option<&str> {
        self.correlation_id.as_deref()
    }
    /// ISO 8601 date-time.
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
}
impl TransactionSummary {
    /// Creates a new builder-style object to manufacture [`TransactionSummary`](crate::types::TransactionSummary).
    pub fn builder() -> crate::types::builders::TransactionSummaryBuilder {
        crate::types::builders::TransactionSummaryBuilder::default()
    }
}

/// A builder for [`TransactionSummary`](crate::types::TransactionSummary).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct TransactionSummaryBuilder {
    pub(crate) id: ::std::option::Option<::std::string::String>,
    pub(crate) account_id: ::std::option::Option<::std::string::String>,
    pub(crate) account_kind: ::std::option::Option<::std::string::String>,
    pub(crate) r#type: ::std::option::Option<crate::types::TransactionType>,
    pub(crate) status: ::std::option::Option<crate::types::TransactionStatus>,
    pub(crate) amount: ::std::option::Option<i64>,
    pub(crate) pool: ::std::option::Option<crate::types::PoolType>,
    pub(crate) direction: ::std::option::Option<crate::types::TransactionDirection>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) void_reason: ::std::option::Option<::std::string::String>,
    pub(crate) merchant_id: ::std::option::Option<::std::string::String>,
    pub(crate) merchant_mcc: ::std::option::Option<::std::string::String>,
    pub(crate) source_ifsc: ::std::option::Option<::std::string::String>,
    pub(crate) source_account: ::std::option::Option<::std::string::String>,
    pub(crate) gateway_ref: ::std::option::Option<::std::string::String>,
    pub(crate) funding_type: ::std::option::Option<::std::string::String>,
    pub(crate) correlation_id: ::std::option::Option<::std::string::String>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl TransactionSummaryBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn account_kind(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.account_kind = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_account_kind(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.account_kind = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_account_kind(&self) -> &::std::option::Option<::std::string::String> {
        &self.account_kind
    }
    /// Transaction type.
    /// This field is required.
    pub fn r#type(mut self, input: crate::types::TransactionType) -> Self {
        self.r#type = ::std::option::Option::Some(input);
        self
    }
    /// Transaction type.
    pub fn set_type(mut self, input: ::std::option::Option<crate::types::TransactionType>) -> Self {
        self.r#type = input; self
    }
    /// Transaction type.
    pub fn get_type(&self) -> &::std::option::Option<crate::types::TransactionType> {
        &self.r#type
    }
    /// Transaction status.
    /// This field is required.
    pub fn status(mut self, input: crate::types::TransactionStatus) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    /// Transaction status.
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::TransactionStatus>) -> Self {
        self.status = input; self
    }
    /// Transaction status.
    pub fn get_status(&self) -> &::std::option::Option<crate::types::TransactionStatus> {
        &self.status
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    /// This field is required.
    pub fn amount(mut self, input: i64) -> Self {
        self.amount = ::std::option::Option::Some(input);
        self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn set_amount(mut self, input: ::std::option::Option<i64>) -> Self {
        self.amount = input; self
    }
    /// Monetary amount in the smallest currency unit (e.g., paise for INR).
    pub fn get_amount(&self) -> &::std::option::Option<i64> {
        &self.amount
    }
    /// Pool type indicating the source of funds.
    pub fn pool(mut self, input: crate::types::PoolType) -> Self {
        self.pool = ::std::option::Option::Some(input);
        self
    }
    /// Pool type indicating the source of funds.
    pub fn set_pool(mut self, input: ::std::option::Option<crate::types::PoolType>) -> Self {
        self.pool = input; self
    }
    /// Pool type indicating the source of funds.
    pub fn get_pool(&self) -> &::std::option::Option<crate::types::PoolType> {
        &self.pool
    }
    /// Transaction direction.
    /// This field is required.
    pub fn direction(mut self, input: crate::types::TransactionDirection) -> Self {
        self.direction = ::std::option::Option::Some(input);
        self
    }
    /// Transaction direction.
    pub fn set_direction(mut self, input: ::std::option::Option<crate::types::TransactionDirection>) -> Self {
        self.direction = input; self
    }
    /// Transaction direction.
    pub fn get_direction(&self) -> &::std::option::Option<crate::types::TransactionDirection> {
        &self.direction
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn void_reason(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.void_reason = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_void_reason(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.void_reason = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_void_reason(&self) -> &::std::option::Option<::std::string::String> {
        &self.void_reason
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn merchant_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.merchant_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_merchant_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.merchant_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_merchant_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.merchant_id
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn merchant_mcc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.merchant_mcc = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_merchant_mcc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.merchant_mcc = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_merchant_mcc(&self) -> &::std::option::Option<::std::string::String> {
        &self.merchant_mcc
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn source_ifsc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.source_ifsc = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_source_ifsc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.source_ifsc = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_source_ifsc(&self) -> &::std::option::Option<::std::string::String> {
        &self.source_ifsc
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn source_account(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.source_account = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_source_account(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.source_account = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_source_account(&self) -> &::std::option::Option<::std::string::String> {
        &self.source_account
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn gateway_ref(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.gateway_ref = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_gateway_ref(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.gateway_ref = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_gateway_ref(&self) -> &::std::option::Option<::std::string::String> {
        &self.gateway_ref
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn funding_type(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.funding_type = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_funding_type(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.funding_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_funding_type(&self) -> &::std::option::Option<::std::string::String> {
        &self.funding_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn correlation_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.correlation_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_correlation_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.correlation_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_correlation_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.correlation_id
    }
    /// ISO 8601 date-time.
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    /// ISO 8601 date-time.
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input; self
    }
    /// ISO 8601 date-time.
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    /// Consumes the builder and constructs a [`TransactionSummary`](crate::types::TransactionSummary).
    /// This method will fail if any of the following fields are not set:
    /// - [`id`](crate::types::builders::TransactionSummaryBuilder::id)
    /// - [`account_id`](crate::types::builders::TransactionSummaryBuilder::account_id)
    /// - [`account_kind`](crate::types::builders::TransactionSummaryBuilder::account_kind)
    /// - [`r#type`](crate::types::builders::TransactionSummaryBuilder::type)
    /// - [`status`](crate::types::builders::TransactionSummaryBuilder::status)
    /// - [`amount`](crate::types::builders::TransactionSummaryBuilder::amount)
    /// - [`direction`](crate::types::builders::TransactionSummaryBuilder::direction)
    /// - [`created_at`](crate::types::builders::TransactionSummaryBuilder::created_at)
    pub fn build(self) -> ::std::result::Result<crate::types::TransactionSummary, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::TransactionSummary {
                id: self.id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("id", "id was not specified but it is required when building TransactionSummary")
                    )?
                ,
                account_id: self.account_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("account_id", "account_id was not specified but it is required when building TransactionSummary")
                    )?
                ,
                account_kind: self.account_kind
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("account_kind", "account_kind was not specified but it is required when building TransactionSummary")
                    )?
                ,
                r#type: self.r#type
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("r#type", "r#type was not specified but it is required when building TransactionSummary")
                    )?
                ,
                status: self.status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("status", "status was not specified but it is required when building TransactionSummary")
                    )?
                ,
                amount: self.amount
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("amount", "amount was not specified but it is required when building TransactionSummary")
                    )?
                ,
                pool: self.pool
                ,
                direction: self.direction
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("direction", "direction was not specified but it is required when building TransactionSummary")
                    )?
                ,
                description: self.description
                ,
                void_reason: self.void_reason
                ,
                merchant_id: self.merchant_id
                ,
                merchant_mcc: self.merchant_mcc
                ,
                source_ifsc: self.source_ifsc
                ,
                source_account: self.source_account
                ,
                gateway_ref: self.gateway_ref
                ,
                funding_type: self.funding_type
                ,
                correlation_id: self.correlation_id
                ,
                created_at: self.created_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("created_at", "created_at was not specified but it is required when building TransactionSummary")
                    )?
                ,
            }
        )
    }
}

