// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListTransactionsOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub transactions: ::std::vec::Vec::<crate::types::TransactionSummary>,
    #[allow(missing_docs)] // documentation missing in model
    pub total: i64,
    #[allow(missing_docs)] // documentation missing in model
    pub offset: i64,
    #[allow(missing_docs)] // documentation missing in model
    pub limit: i64,
}
impl  ListTransactionsOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn transactions(&self) -> &[crate::types::TransactionSummary] {
        use std::ops::Deref; self.transactions.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn total(&self) -> i64 {
        self.total
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn offset(&self) -> i64 {
        self.offset
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(&self) -> i64 {
        self.limit
    }
}
impl ListTransactionsOutput {
    /// Creates a new builder-style object to manufacture [`ListTransactionsOutput`](crate::operation::list_transactions::ListTransactionsOutput).
    pub fn builder() -> crate::operation::list_transactions::builders::ListTransactionsOutputBuilder {
        crate::operation::list_transactions::builders::ListTransactionsOutputBuilder::default()
    }
}

/// A builder for [`ListTransactionsOutput`](crate::operation::list_transactions::ListTransactionsOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListTransactionsOutputBuilder {
    pub(crate) transactions: ::std::option::Option<::std::vec::Vec::<crate::types::TransactionSummary>>,
    pub(crate) total: ::std::option::Option<i64>,
    pub(crate) offset: ::std::option::Option<i64>,
    pub(crate) limit: ::std::option::Option<i64>,
}
impl ListTransactionsOutputBuilder {
    /// Appends an item to `transactions`.
    ///
    /// To override the contents of this collection use [`set_transactions`](Self::set_transactions).
    ///
    pub fn transactions(mut self, input: crate::types::TransactionSummary) -> Self {
        let mut v = self.transactions.unwrap_or_default();
                        v.push(input);
                        self.transactions = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_transactions(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::TransactionSummary>>) -> Self {
        self.transactions = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_transactions(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::TransactionSummary>> {
        &self.transactions
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn total(mut self, input: i64) -> Self {
        self.total = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_total(mut self, input: ::std::option::Option<i64>) -> Self {
        self.total = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_total(&self) -> &::std::option::Option<i64> {
        &self.total
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn offset(mut self, input: i64) -> Self {
        self.offset = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_offset(mut self, input: ::std::option::Option<i64>) -> Self {
        self.offset = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_offset(&self) -> &::std::option::Option<i64> {
        &self.offset
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn limit(mut self, input: i64) -> Self {
        self.limit = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_limit(mut self, input: ::std::option::Option<i64>) -> Self {
        self.limit = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_limit(&self) -> &::std::option::Option<i64> {
        &self.limit
    }
    /// Consumes the builder and constructs a [`ListTransactionsOutput`](crate::operation::list_transactions::ListTransactionsOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`transactions`](crate::operation::list_transactions::builders::ListTransactionsOutputBuilder::transactions)
    /// - [`total`](crate::operation::list_transactions::builders::ListTransactionsOutputBuilder::total)
    /// - [`offset`](crate::operation::list_transactions::builders::ListTransactionsOutputBuilder::offset)
    /// - [`limit`](crate::operation::list_transactions::builders::ListTransactionsOutputBuilder::limit)
    pub fn build(self) -> ::std::result::Result<crate::operation::list_transactions::ListTransactionsOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::list_transactions::ListTransactionsOutput {
                transactions: self.transactions
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("transactions", "transactions was not specified but it is required when building ListTransactionsOutput")
                    )?
                ,
                total: self.total
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("total", "total was not specified but it is required when building ListTransactionsOutput")
                    )?
                ,
                offset: self.offset
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("offset", "offset was not specified but it is required when building ListTransactionsOutput")
                    )?
                ,
                limit: self.limit
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("limit", "limit was not specified but it is required when building ListTransactionsOutput")
                    )?
                ,
            }
        )
    }
}

